### ISSUE TITLE
Deployment Labels are too broad for cluster-bootstrap-controller

### ISSUE THREAD

**Issue by bigkevmcd** [weaveworks/weave-gitops-enterprise#1008]
**WGE release:**
v0.8.1

**Kubernetes release:**

**Priority**
 - medium

**Describe the bug**

`cluster-bootstrap-controller`'s deployment has this selector:
```yaml
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      control-plane: controller-manager
```

`cluster-controller` gets these labels:
```yaml
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: weave-gitops-enterprise
      app.kubernetes.io/name: cluster-controller
      control-plane: controller-manager
```

This means that `cluster-bootstrap-controller` sees `cluster-controller` pods as part of its pods.

**To Reproduce**
Install both cluster-bootstrap-controller and cluster-controller and run

```
$ kubectl logs deploy/weave-gitops-enterprise-mccp-cluster-bootstrap-controller -n flux-system
```
The logs from the cluster-service will be output.

**Expected behaviour**
Logs only from cluster-bootstrap-controller should be fetched.

**Additional context**
