### ISSUE TITLE
Applications/sources page: empty page if any one cluster fails to connect

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#1069]
**Previous attempts to fix**

We addressed some cases here in https://github.com/weaveworks/weave-gitops/issues/2067 this now includes partial results if there was an RBAC or similar error _after_ successfully connecting to a cluster. But if the connection itself fails then we still show no results at all.

**Desired behaviour**

But we need to make it a bit more resilient still. We should return partial results for the rest of the clusters (including management cluster), if one of them fails for some reason.

We should also address https://github.com/weaveworks/weave-gitops/issues/2069 (show error message in the UI too).

**To repro**

- `tilt up` (?) or get a WGE installation going
- add a cluster with a bad kubeconfig secret:[0]
- notice nothing is returning in applications
- notice opening devtools we see the response:

```
code: 2
details: []
message: "error getting impersonating client: failed adding cluster client to pool: failed to create leaf client: Get \"https://172.18.0.123:6443/api?timeout=32s\": dial tcp 172.18.0.123:6443: connect: no route to host"
```

"Bad cluster":

```yaml
apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  name: demo120-broke
  namespace: default
spec:
  secretRef:
    name: demo-broke-kubeconfig-2
```

secret with a bad IP:
```yaml
apiVersion: v1
data:
  value: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VNMmFrTkRRV1JMWjBGM1NVSkJaMGxDUVVSQlRrSm5hM0ZvYTJsSE9YY3dRa0ZSYzBaQlJFRldUVkpOZDBWUldVUldVVkZFUlhkd2NtUlhTbXdLWTIwMWJHUkhWbnBOUWpSWVJGUkplVTFFVlhsT1ZFVXhUWHBGTVUweGIxaEVWRTE1VFVSVmVVMXFSVEZOZWxreFRURnZkMFpVUlZSTlFrVkhRVEZWUlFwQmVFMUxZVE5XYVZwWVNuVmFXRkpzWTNwRFEwRlRTWGRFVVZsS1MyOWFTV2gyWTA1QlVVVkNRbEZCUkdkblJWQkJSRU5EUVZGdlEyZG5SVUpCVGtwc0NsWmxPVUZyUWtORlkzbHFMemhDVFhWbVVrRkNXazVSUkVReE4zQTJNR3BWTUZaa1JITkpRM2t3TW5Kc2RFVnBOMnRaTnpaa1pFbDROVzkzVG5WdFMwa0tUbTE1UmxKbVZXSlpkbmR0UVdKbmFXTTJibFpFTUZSWGNHMUpMME5hVHpWcU5rZDFURkJ0ZG14aVRqbFhibVpQVERSWVZXZE1RMlV5V1RoTVprbFBRUW81UW0xaGFFZFRRV05OVWxKblZVNXdLM2t2UVhWQ1Uxb3hUMEkyY0c1T1FrbDNaV3dyV1hoSWFpOTFVR1J5TkVGamFscGljVlJxWm5KbllXRm1VMEV6Q2k4eVZqazFibXMzUkVJMlJTOW9WRE5RZUVWeE1FNXJXR2RCUkVoMmRWQndMMU5yVlhWSmRrUkdWRWg2YjJsdWJXczNkRGN2ZWtRclEzRmxOMVo2VWxjS1EwTmlTemRDY1VSRk5FNVdXRTl6ZGtGallqbHlUeXM0VDJzNVFVTXZTVGQyY0V4bFJEZzJkRkJYUm5sTFpFRnhNelpJYm1VMGFWQndkWGx0YTA5YVFRcDVTblJ6V1V0SmRXaERjVk53YTFkUVRERmpRMEYzUlVGQllVNUdUVVZOZDBSbldVUldVakJRUVZGSUwwSkJVVVJCWjB0clRVSkpSMEV4VldSRmQwVkNDaTkzVVVsTlFWbENRV1k0UTBGUlFYZElVVmxFVmxJd1QwSkNXVVZHU1ZCU09FaEZZVzFYS3pWbE16RlNZV2hFWTJaRlIxZFdOR1ExVFVFd1IwTlRjVWNLVTBsaU0wUlJSVUpEZDFWQlFUUkpRa0ZSUWtOUFdHWTJSVFZVYlVVclpVeGpRV3R2UmtWVGEya3lORFZoTm5ablJqZGxNVXBrTDFNeWNtSmtkVmt3ZGdwYWNsWjVOV0pVVVc1Mk1GQlNVRTlWYzJGaFFUSkdVVmhJYUhwRUwxSk9XRFprTDNVMVlsVlphSEJxYjJ4eVJWSnJTR05yYmpWRFRWSklUbU5JTVdrd0NqTmxha2w0ZUhaUlkwSmhVVXd4UVhFMlVXZFNLMUlyWldsSFJXSjVjalpVY0RaNE9WVm1hVGRpY201UWQyOVpiMnB2VmpSelFVVTRlSGxEWVdKMWRsY0tkMloyUWtSVlkyWTRNblJDTmpGdGJXTm9hVXAwZVdSQk5EUXJjRTFVZDFsbmJsazVZbXN5VDJGcU1XaHpVVUU0VVVkSWF6bHBhVGgzYkdkTk1XeE9kUXBFWlRWcU5sUjZXbVpqWjFwS2FsaG5jRGQ0Y25jMllWTXlSRVJUVkM5M09WSm5hM2x5TlRaNWNWZ3dRMHRVYkhFek5XWTFURVp3WjFWYWNFWXpWazVLQ2xSU1VISTVaR05wTWtaa05WcFBUakpYU0dScU1qRnRaM2RKVVRaWVZtbzNTblJaWmtkRVQyd0tMUzB0TFMxRlRrUWdRMFZTVkVsR1NVTkJWRVV0TFMwdExRbz0KICAgIHNlcnZlcjogaHR0cHM6Ly8xNzIuMTguMC4xMjM6NjQ0MwogIG5hbWU6IGRlbW8tMDEyMApjb250ZXh0czoKLSBjb250ZXh0OgogICAgY2x1c3RlcjogZGVtby0wMTIwCiAgICB1c2VyOiBkZW1vLTAxMjAtYWRtaW4KICBuYW1lOiBkZW1vLTAxMjAtYWRtaW5AZGVtby0wMTIwCmN1cnJlbnQtY29udGV4dDogZGVtby0wMTIwLWFkbWluQGRlbW8tMDEyMApraW5kOiBDb25maWcKcHJlZmVyZW5jZXM6IHt9CnVzZXJzOgotIG5hbWU6IGRlbW8tMDEyMC1hZG1pbgogIHVzZXI6CiAgICBjbGllbnQtY2VydGlmaWNhdGUtZGF0YTogTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVUkZla05EUVdaMVowRjNTVUpCWjBsSllubDNlWHBrYVU5WFRsVjNSRkZaU2t0dldrbG9kbU5PUVZGRlRFSlJRWGRHVkVWVVRVSkZSMEV4VlVVS1FYaE5TMkV6Vm1sYVdFcDFXbGhTYkdONlFXVkdkekI1VFdwQk1VMXFWWGhPVkUxNFRsUk9ZVVozTUhsTmVrRXhUV3BWZUU1VVRUSk9WRlpoVFVSUmVBcEdla0ZXUW1kT1ZrSkJiMVJFYms0MVl6TlNiR0pVY0hSWldFNHdXbGhLZWsxU2EzZEdkMWxFVmxGUlJFVjRRbkprVjBwc1kyMDFiR1JIVm5wTVYwWnJDbUpYYkhWTlNVbENTV3BCVGtKbmEzRm9hMmxIT1hjd1FrRlJSVVpCUVU5RFFWRTRRVTFKU1VKRFowdERRVkZGUVd3MUsxUlpkaTl0UVZGQ1Vrc3lMMFVLV0daVmRsZEpOalowY3pFNVZGZENkMkpxV2l0cmMxQlhka1JxV1ZsbmIwMXpZamh1T0d4dGVYaEdNbVJ3Tm1aUU4zWkpjbm8yTWt0TlRtUnRaRGRVU3dwclFWUXdUV3R3YWtKRmVXMVdZamxNTnpoMlEySnVWV1J6UzJKdmNXSmFUVlJWVEV4QmEySmhWM2s1Vm1GQlVXZHFkR1l6V1hoRUwzRnJTa3RLZVROdkNrSktUbTAyV1d3MVluZ3hiVmhGVDI5VE5HWnViRTVNV1M5RE1HeEVWbU5PZUVsNWFFdE5Ra1pXU1dwV1JFRTNNMk4wVmtsMmFuWlJWMGgxYVRCc1J6RUtjVEJ4TW10NFNVRldkWEZoVmtnMmFHaHZhRkY2UkhWak9YQmtaRTExYm5scWVqSmpWRzl4WVhGNU9FeHdjbUpRZVhsWFdGYzVUMlE0ZWsxd2RVWnNiUXBZZEhVclZHeEdkekZ2U0hkRmN6RklZMVJZTjFkeVIxQm5SRUpUSzFONVMyTlJWWHBWWmxoQlR6WlpSazlxTUdZelozQldNRE5rZW5GemEwMWlOV1JJQ21kdlZEZFpkMGxFUVZGQlFtOHdaM2RTYWtGUFFtZE9Wa2hST0VKQlpqaEZRa0ZOUTBKaFFYZEZkMWxFVmxJd2JFSkJkM2REWjFsSlMzZFpRa0pSVlVnS1FYZEpkMGgzV1VSV1VqQnFRa0puZDBadlFWVm5PVWgzWTFKeFdtSTNiRGRtVmtaeFJVNTRPRkZhV2xob00ydDNSRkZaU2t0dldrbG9kbU5PUVZGRlRBcENVVUZFWjJkRlFrRklORGxFZURCNFdsSndWMnA0VDJsdFozVmxMMUZ6YW1zd1RFRkRiRFp3V21OV1ZGcHNaV3RCYm05TWFYWmxkMHcxWkRCclpVWndDblF3WVhnMlVtbENhMnRSUW1WbVEwTk9lRTVtWWxsUlpEWk9TRnBUYlRGc05sWTFRbnBzVm5ZMFNIQlBiVUoyY0RaUU5YUkxUSGMxYkd0Rk5VZEhWMlVLZW1wbWFqUmxWVmQ1VmtGblJqVkNSRnBqVDIweE5HOU5kR05aZEVabWNISlJVSE5RUTBoQmVsSXJOSEJ0UlhkTlVUTXhiakJJYUZGbGNXZFphbTFEVWdweWVYQnRVa2RoV2xNeU9WQkVRbkpTWkhCSmJWbEtUa0k1UmxkWVUyWTJWelJxVjFaTGNsVklVMEZ5ZW1oaFVHeHlWRXB4YkRGcFRUaFVjbUl6ZFZGbENuQjZPR3BJTUVOSVFWZHRhR2RuT1VSWVJXMXpiRlZJWms5TE9VVnpNRVJVYlRWRWVsbHFTR2xrYmt0R1RHdDFiSGxuWjNGRGIzSjNjV3BMVFdaUGFuWUtNWGt6Wm13M1prRlJMM05IZDBKMmMwaDZTblJyVkRSUmRHSnZlbnBLZHowS0xTMHRMUzFGVGtRZ1EwVlNWRWxHU1VOQlZFVXRMUzB0TFFvPQogICAgY2xpZW50LWtleS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJTVTBFZ1VGSkpWa0ZVUlNCTFJWa3RMUzB0TFFwTlNVbEZiMmRKUWtGQlMwTkJVVVZCYkRVclZGbDJMMjFCVVVKU1N6SXZSVmhtVlhaWFNUWTJkSE14T1ZSWFFuZGlhbG9yYTNOUVYzWkVhbGxaWjI5TkNuTmlPRzQ0YkcxNWVFWXlaSEEyWmxBM2RrbHllall5UzAxT1pHMWtOMVJMYTBGVU1FMXJjR3BDUlhsdFZtSTVURGM0ZGtOaWJsVmtjMHRpYjNGaVdrMEtWRlZNVEVGclltRlhlVGxXWVVGUloycDBaak5aZUVRdmNXdEtTMHA1TTI5Q1NrNXRObGxzTldKNE1XMVlSVTl2VXpSbWJteE9URmt2UXpCc1JGWmpUZ3A0U1hsb1MwMUNSbFpKYWxaRVFUY3pZM1JXU1hacWRsRlhTSFZwTUd4SE1YRXdjVEpyZUVsQlZuVnhZVlpJTm1ob2IyaFJla1IxWXpsd1pHUk5kVzU1Q21wNk1tTlViM0ZoY1hrNFRIQnlZbEI1ZVZkWVZ6bFBaRGg2VFhCMVJteHRXSFIxSzFSc1JuY3hiMGgzUlhNeFNHTlVXRGRYY2tkUVowUkNVeXRUZVVzS1kxRlZlbFZtV0VGUE5sbEdUMm93WmpObmNGWXdNMlI2Y1hOclRXSTFaRWhuYjFRM1dYZEpSRUZSUVVKQmIwbENRVUpPYkd4eVZsUm9NV3RhWTFWcVpBcFJORWhDYmtGNk5FNVhjWFJZZUhCSEwwSnpaRmhhVUc4cll5dGhaR2hSVlhSUmMwbExWbEZZY0ZsaU5XTjJSeTk0YUc5TVdWRTVkMWt2TVdKclVVRXZDbGxMY1V3NU4wWXpWWEpPTmtkek1XUmhOVzFDZERVemNETmhTamQwT0dZclUydFRXVUoxUTBSeUszUTJXWEpMY2pGSU5YaHZibEpLSzBkelVHb3Jlbm9LVFc1MGFsbEJZMEZVTUdsdWRXcERWR1I2VVhsaWNUTmlVekppTTB4U2NFZGtNbEJCV0ZOaU5sSk9LM0VyU1ZoTldTOW9aSFkxTVdZemRIZENRbWhhZWdveVoxUXhZM0UzVm5WcmRIaFZWbWRMYkRaSWRWWmFWME01WTI1cVNGSktZV1ZaZFdjdk1rSk5lRGx0YUc5aFlUQmxRemhRVjJkVVYxWmllbU5yWm00MkNuaDJjbXhKYWk5c1VVVmpWV0kzUlVWNFNIaHlTVVJMWkV4TFJsQjZOSEZwV1ZWWlZURTVaelJMUmxWSGJrNXFTazVFWVVsMk1GbEVZakl5UkhadGJHb0tiRVF5YVdablJVTm5XVVZCZVZwdFFqUnBPVUZEVWtWTWRFOVdjSEEwVm5ZM1RYZENTMVpZVmxneWEzY3phV2RrY1VSbFJtaGtObTFVYVhkeU4xTXlSUXBrVlRSMFltaERNbmQwZGt0UFoyMTNTa3M0YTFsWE9XNWFUREJWWTI1emVHZFVTMnQzVlhGSWVEZE5SMjVoUWprdmNVeGpPVFJQTjNCaGF6QkRZMkZYQ2tsTlp6TnJOVGcwZDNoSmR6WklSVWRvT1RCWlZuRXpNazR6U21WcFRVdFZiemRPT1V4TU5GZEtVMnRPVkRsdVl6RnBaWFZsUlRCRFoxbEZRWGRKYlRFS1dGSndkblptYlhSWVRsVTNkMGsxU25aR1lXNWhPRlU1YUVwd1NuVnBNVkl4ZGxKSFlrTXhVeTlXTkhSTU9IYzNTMDluVFN0b1JFSkdhM0pzVjJwT1FncFJabUU1UXlzMWJWbGlVWEZaUkRWcVNraHJRbWxVZWtWTU5EZERhMVZTY1VORmRFTlRTbVZOUWtoTlJqUkZWRUZSS3k5WlduUk5RVzh6UVZCbmVVVkNDbVp0YXpoRlpuUjVNRXhDYkU5M1ZXNUlSM05vTDJGUU1FMWhaRUpRUXpoVFpFUXZSRWR0T0VObldVSndjblZPTnpSNlJUWnFOR3RJYURoNFpsZFpRbGdLVEc5eVpGWklXRXN3Y1ZsbWEwRkJZMFY0T0ZsRmNWRXdSSE4yYjFKb2FFOU9ia1o1V21GcGNHUm1ZMHBtWkV0MFMwaE9NVGhMVkZCR2NVRkdZemRrTndvNU1GTlFXRGRpVjFwWE9YVmhjR2RwVTA1YU1XMXpWbWRFZEdWTk1rZEpWRkpYU2psTVRtSm5la1ZTTDFabFJVdHJSV3RYUWpWUmRtUlFSa0l5UmprM0NtZGlhRFZKUWpCVU1XWldOR2x6YkU5TGRtTXpZMUZMUW1kRVRHTTNhbFl2VVRFck4yTnhibWRvZERGNVpWWlpkM2xvS3pGU2JrRmxWbXBZUW5aVGJqZ0tPVUpIYkRBMVQzUmhiVU5FU1cxdVNFTTBObEZIU1VselNGQlRPRXcxVVdWbE5HbEpXRlJIV1ZvNE1YWkVZaTlZTWpaclIycFpiRWQyUnpKc01XbEZSUXA1UzJwdGNVRXlVVEpWSzB0MVoxQTBaVFJIUjFsc1prdDRZalZPV0U1cGNFMXFOVW96SzFoNlp6TnhXUzlQUlUxRFJHMDJUVEIwWlhSUFVWTlNNWHBCQ21JeWEzWkJiMGRCU1ZGemFHbFZkSGh5VmtGMVdXSktNWGh0Y1hCdk1tRkpWWEl4WXpnNVRrZEVSV0pYTmt0UE9IQkJWa3AyVUd4aU1rdFhNRlZGV2swS2VXVjRWWEZtTUV0d2RuUjFTa2xYWTBnNFpDdGhjbk5IZFM5RldFZHdUbnA2YkRCMGNYVnBNRXQwVXpSNmFWRkpZMGt5Y1dkcFQwOXJiamxrZVZKa1ZncEVOMk5JTUU5b01rTTJaRkE0ZDIxT09HdFFaMlY1Ykd0NFlWbDZVRkZ2T1ZsamVYRkNkVGxVVlVFdmVYZFRVakExY1RBOUNpMHRMUzB0UlU1RUlGSlRRU0JRVWtsV1FWUkZJRXRGV1MwdExTMHRDZz09Cg==
kind: Secret
metadata:
  name: demo-broke-kubeconfig-2
  namespace: default
type: Opaque
```
