### ISSUE TITLE
[BE] Add endpoint to add workloads to a cluster

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#1077]
Add a new endpoint (e.g. `POST /v1/enterprise/kustomizations`) that will accept:

- a **list** of `{ kustomization, cluster }`, maybe we support all fields, but at least
  - `k.metadata.name`: name, required
  - `k.metadata.namespace`: namespace, default: `flux-system`
  - `k.spec.path`: some path in the repo, required
  - `k.spec.sourceRef.name`: required, name of the gitrepo object
  - `k.spec.sourceRef.namespace`: required, namespace of the gitrepo object
  - `cluster.name` required, cluster name (OR supply a filePath)
  - `cluster.namespace` required, cluster namespace (OR suppy a filePath)
- repository and commit info
  - The usual[1] 
- A filePath to write the kustomization to in the management git repo that should default to `./clusters/{clusterName}/{clusterNamespace/{name}-kustomziations.yaml`

And then it will create:
 - a commit in the provided repository URL with the given title/description[1]
 - pull request in the provided repository URL with the given title description[1]

### For example!

```yaml
request:
  repositoryUrl: https://github.com/my-org/my-management-cluster
  headBranch: adds-kustomizations-abdg2751bs
  baseBranch: main
  title: Adds capi apps to management and billing apps to dev/billing
  description: Adds capi apps to management and billing apps to dev/billing
  data:
    - cluster:
        name: management
        namespace: default
        # This is how we signal the management cluster right now..
        isControlPlane: true
      kustomization:
        metadata:
          name: apps-capi
          namespace: flux-system
        spec:
          path: ./apps/capi
          sourceRef:
            name: flux-system
            namespace: flux-system
    - cluster:
        name: billing
        namespace: dev
      kustomization:
        metadata:
          name: apps-billing
          namespace: flux-system
        spec:
          path: ./apps/billing
          sourceRef:
            name: flux-system
            namespace: flux-system
```
```yaml
response:
  webURL: https://github.com/my-org/my-management-cluster/pull/1077
```
```yaml
pullrequest:
  files:
    # note no namespace when management
    - ./clusters/management/flux-system/apps-capi-kustomization.yaml
    - ./clusters/dev/billing/flux-system/apps-billing-kustomization.yaml
```

---

[0] sample kustomization when written out to git
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/management
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```
