### ISSUE TITLE
[BE] Update create-cluster-pr endpoint to accept list of workloads

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#1079]
We already have an endpoint `POST /v1/clusters`.

We should adapt it so that we can additionally provide a list of `kustomizations` in the request.

E.g.! 
```yaml
request:
  repositoryUrl: https://github.com/my-org/my-management-cluster

  # ...
  # ALL_THE_USUAL_KEYS: GO HERE
  # ...

  kustomizations:
    - metadata:
        name: apps-capi
        namespace: flux-system
      spec:
        path: ./apps/capi
        sourceRef:
          name: flux-system
          namespace: flux-system
    - metadata:
        name: apps-billing
        namespace: flux-system
      spec:
        path: ./apps/billing
        sourceRef:
          name: flux-system
          namespace: flux-system

response:
  webURL: https://github.com/my-org/my-management-cluster/pull/1077

pullrequest:
  # additional files will be written
  files:
    - ./clusters/dev/billing/flux-system/apps-capi-kustomization.yaml
    - ./clusters/dev/billing/flux-system/apps-billing-kustomization.yaml
```
