### ISSUE TITLE
[BE] Add policy to restrict which clusters users can deploy to

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#1106]
We want to restrict the values you are allowed to provide in Kustomizations's kubeconfig field:

https://fluxcd.io/docs/components/kustomize/api/#kustomize.toolkit.fluxcd.io/v1beta2.KubeConfig

```yaml
tenants:
  # list of secrets that contains kubeconfigs to other linked clusters
  allowClusters:
  - kubeConfig: test-cluster-kubeconfig

```

This should generate some policy that will restrict `Kustomization` CRs from being created.

- If the kustomization has a `spec.kubeConfig` set, then the kubeConfig has to be in the allowed list in `tenants.yaml`

See also: https://fluxcd.io/docs/components/kustomize/kustomization/#remote-clusters--cluster-api

> **Note**
> There are some `serviceAccount` implications here but lets consider and implement them in another issue
