### ISSUE TITLE
[UI, BE] As a User, I can see the infra provider of the cluster in the GUI so that I have a visual cue where the cluster is provisioned

### ISSUE THREAD

**Issue by davidstauffer** [weaveworks/weave-gitops-enterprise#1165]
[UI, BE] As a User, I can see the infra provider of the cluster in the GUI so that I have a visual cue on what infra the cluster is provisioned

Currently, we don't show on what infra the cluster is provisioned(AKS, EKS, Liquid metal) and what type it is (Managed vs unmanaged).
The CAPI objects give us that information.
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cni: cilium
    weave.works/capi: bootstrap
  name: prod23
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 172.25.0.0/16
    services:
      cidrBlocks:
      - 172.26.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: prod23-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: MicrovmCluster
    name: prod23
```

My suggestion is that we use the `infrastructureRef` to render a visual cue ( We had icons in the past ) + the kind in the table. Another driver for that is the Kubernetes everywhere demo scenario that we are showing to customers, if we have in the table cluster easily distinguishable between different infra providers, it will make the point that we run on any infrastructure.

Thoughts @foot @AlinaGoaga @bia
