### ISSUE TITLE
[add-app][spike] Enhanced `params.options` for creating resources via templates

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#1201]
We currently support:

```yaml
apiVersion: capi.weave.works/v1alpha1
kind: CAPITemplate
metadata:
  name: cluster-template-development
  namespace: default
spec:
  params:
    - name: KUBERNETES_VERSION
      description: Kubernetes version to use for the cluster
      options: ["1.19.11", "1.21.1", "1.22.0", "1.23.3"]
```

We'd like to extend this so the UI can provide a richer experience for Users by providing runtime objects in the `options` array. For example:

```yaml
spec:
  params:
    - name: GIT_REPO
      optionResources:
        kind: GitRepository
```

The user would then be presented with a dropdown in the UI, that would show all the available `GitRepository` CRs available to them in the cluster (response from `/v1/gitrepositories`).

### Details

This is a spike so we can explore, whatever works fairly quickly. Maybe the UI then sends:
```yaml
params:
  GIT_REPO: `{ "name": "my-repo", "namespace": "flux-system", "clusterName": "dev-01" }`
```

The template parsing could then check if `GIT_REPO` is an `optionResources` and inject a few more keys. Or something.

Which we make available in the template as `{{ .params.GIT_REPO.name }}` etc _or_ `${GIT_REPO__NAME}`, we could start with support for just one of them, whatever is easier.
