### ISSUE TITLE
[BE,UI] As a User, I want to observe the status of my TF controller primitives/objects so that I can understand and reason about the state

### ISSUE THREAD

**Issue by davidstauffer** [weaveworks/weave-gitops-enterprise#1208]
We want to improve the TF observability and user experience in Weave GitOps. The MVP of TF templating with the GitOps templates is only a part of the overall experience.

The TF controller uses an object very similar to a kustomization. Find more [here](https://weaveworks.github.io/tf-controller/getting_started/). 
```
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: "auto"
  path: ./
  sourceRef:
    kind: GitRepository
    name: helloworld
    namespace: flux-system
```

We want to render those objects similar in the GUI as we do for kustomizations and helmReleases in the applications tab in the GUI.

Find [here](https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?node-id=10327%3A60844) the figma HF.
![image.png](https://images.zenhubusercontent.com/60803425bb523c39cfb61e51/b26add97-661c-43a7-bce5-7469afeadfeb)

Additionally, we want to have Terraform as its own high-level menu feature, so that it can be easily discovered by the user.
The TF templates will be located as a submenu item there. (See HF)

That's the remaining work, that should get the TF feature in WGE to general availability. 
Thoughts and feedback @foot @ahussein3 @bia
