### ISSUE TITLE
Define pipeline API in protobuf

### ISSUE THREAD

**Issue by yiannistri** [weaveworks/weave-gitops-enterprise#1241]
This story is about defining the gRPC model that represents a Pipeline resource in our API. An operation for returning a list of Pipeline resources should also be defined.

The Pipeline CRD is currently undefined but it should look like this based on [our proposal](https://github.com/weaveworks/weave-gitops-private/tree/main/docs/rfcs/0001-pipelines#story-1)

```
apiVersion: pipelines.wego.weave.works/v1alpha1
kind: Pipeline
metadata:
  name: podinfo
  namespace: default
spec:
  environments:
    - name: dev
      targets:
        - namespace: podinfo
          clusterRef:
            kind: GitopsCluster
            name: dev
    - name: prod
      targets:
        - namespace: podinfo
          clusterRef:
            kind: GitopsCluster
            name: prod
```

Related context:
We'll start by showing the following 3 columns: *Application*,*Type*,*Environments*, other columns will follow later as and when we build the functionality.

Acceptance criteria:
- A definition of the gRPC message that represents a Pipeline (including any nested messages)
- A definition of the operation that returns a list of Pipeline resources
