### ISSUE TITLE
Scaffold initial CRD/controller using kubebuilder

### ISSUE THREAD

**Issue by yiannistri** [weaveworks/weave-gitops-enterprise#1248]
This story is about creating the Pipeline CRD and associated controller in the new repo `pipeline-controller`.

```yaml
apiVersion: pipelines.delivery.weave.works/v1alpha1
kind: Pipeline
metadata:
  name: podinfo
  namespace: default
spec:
  environments:
    - name: dev
      targets:
        - namespace: podinfo
          clusterRef:
            kind: GitopsCluster
            name: dev
    - name: prod
      targets:
        - namespace: podinfo
          clusterRef:
            kind: GitopsCluster
            name: prod
```

[Terminology](https://www.notion.so/weaveworks/CD-Pipeline-39a6df44798c4b9fbd140f9d0df1212a#e944087b2380450d854cea118a653936)

[RFC](https://github.com/weaveworks/weave-gitops-private/tree/main/docs/rfcs/0001-pipelines)
