### ISSUE TITLE
Dashboard keeps on showing unnecessary errors for resources a tenant has no permissions

### ISSUE THREAD

**Issue by saeedfazal** [weaveworks/weave-gitops-enterprise#1422]
Let's assume a tenant has no permissions to list/view clusters and templates. The dash board keeps on showing errors at regular intervals.

```
tenants:
  - name: test-team
    namespaces:
    - test-system
    teamRBAC:
      groupName: wge-test
      rules:
        - apiGroups: [""]
          resources: ["secrets", "pods" ]
          verbs: [ "get", "list" ]
        - apiGroups: ["apps"]
          resources: [ "deployments", "replicasets"]
          verbs: [ "get", "list" ]
        - apiGroups: ["kustomize.toolkit.fluxcd.io"]
          resources: [ "kustomizations" ]
          verbs: [ "get", "list", "patch" ]
        - apiGroups: ["helm.toolkit.fluxcd.io"]
          resources: [ "helmreleases" ]
          verbs: [ "get", "list", "patch" ]
        - apiGroups: ["source.toolkit.fluxcd.io"]
          resources: [ "buckets", "helmcharts", "gitrepositories", "helmrepositories" ]
          verbs: [ "get", "list", "patch" ]
        - apiGroups: [""]
          resources: ["events"]
          verbs: ["get", "watch", "list"]  
```

The error bar appears on every page. It would be nice if the error is restricted to templates and clusters page only.
Similarly the sources page error message is not helpful if a tenant has not permissions to view sources in the `flux-system` namespace. 
It would be good user experience if the errors related to permissions/tenancy should follow the similar patterns for all dashboard pages.

![Screenshot 2022-08-31 at 16.14.14.png](https://images.zenhubusercontent.com/60be1f965b600cfd5b5771fb/7ce09d22-4162-42b3-b377-e856f65d3af5)

![Screenshot 2022-09-01 at 10.10.59.png](https://images.zenhubusercontent.com/60be1f965b600cfd5b5771fb/1ed4ca4c-2732-41fd-90c1-e986a02a8529)

![Screenshot 2022-09-01 at 10.13.02.png](https://images.zenhubusercontent.com/60be1f965b600cfd5b5771fb/611a7160-6e96-49d1-b56b-819ba9ee5992)

![Screenshot 2022-09-01 at 10.13.09.png](https://images.zenhubusercontent.com/60be1f965b600cfd5b5771fb/2b4d4736-7a68-4ec1-b1e4-0184b5029daa)
