### ISSUE TITLE
Multiple groups association is not supported in tenant manifest yaml

### ISSUE THREAD

**Issue by saeedfazal** [weaveworks/weave-gitops-enterprise#1435]
A user can not associate multiple groups to the tenant RBAC through `tenant.yaml `manifest.

```
tenants:
  - name: test-team
    namespaces:
    - test-kustomization
    - test-system
    teamRBAC:
      groupName: 
      - weaveworks:QA
      - weaveworks:Pesto
      rules:
        - apiGroups: ["apps"]
          resources: [ "deployments", "replicasets"]
          verbs: [ "get", "list" ]
        - apiGroups: ["kustomize.toolkit.fluxcd.io"]
          resources: [ "kustomizations" ]
          verbs: [ "get", "list", "patch" ]
        - apiGroups: ["helm.toolkit.fluxcd.io"]
          resources: [ "helmreleases" ]
          verbs: [ "get", "list", "patch" ]
        - apiGroups: ["source.toolkit.fluxcd.io"]
          resources: [ "buckets", "helmcharts", "gitrepositories", "helmrepositories" ]
          verbs: [ "get", "list", "patch" ]
```
