### ISSUE TITLE
pre-flight-checks for policies is not working 

### ISSUE THREAD

**Issue by saeedfazal** [weaveworks/weave-gitops-enterprise#1448]
`pre-flight-checks` doesn't throw any error whether policies CRD exists or not. In either scenario `gitops create tenant` tries to deploy the generated resources directly to the cluster. 

**tenants-sources.yaml** 
```
tenants:
  - name: test-team
    namespaces:
    - test-system
    allowedRepositories:
    - kind: GitRepository
      url: https://github.com/stefanprodan/podinfo
    teamRBAC:
      groupName: weaveworks:QA
      rules:
        - apiGroups: [""]
          resources: ["secrets", "pods" ]
          verbs: [ "get", "list" ]
        - apiGroups: ["apps"]
          resources: [ "deployments", "replicasets"]
          verbs: [ "get", "list" ]
        - apiGroups: ["kustomize.toolkit.fluxcd.io"]
          resources: [ "kustomizations" ]
          verbs: [ "get", "list", "patch" ]
        - apiGroups: ["helm.toolkit.fluxcd.io"]
          resources: [ "helmreleases" ]
          verbs: [ "get", "list", "patch" ]
        - apiGroups: ["source.toolkit.fluxcd.io"]
          resources: [ "buckets", "helmcharts", "gitrepositories", "helmrepositories", "ocirepositories" ]
          verbs: [ "get", "list", "patch" ]
        - apiGroups: [""]
          resources: ["events"]
          verbs: ["get", "watch", "list"]
```

```
saeed@Saeeds-MBP weave-gitops-enterprise % kubectl get crd policies.pac.weave.works 
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "policies.pac.weave.works" not found

saeed@Saeeds-MBP weave-gitops-enterprise % gitops --endpoint https://weave.gitops.enterprise.com:30080 --insecure-skip-tls-verify --username wego-admin --password wego-enterprise create tenants --from-file test/utils/data/tenants-sources.yaml --skip-preflight-checks false
namespace/test-system created
serviceaccount/test-team created
rolebinding.rbac.authorization.k8s.io/test-team created
role.rbac.authorization.k8s.io/test-team-team-role created
rolebinding.rbac.authorization.k8s.io/test-team-team-rolebinding created
Error: failed to create resource weave.policies.tenancy.test-team-allowed-repositories: no matches for kind "Policy" in version "pac.weave.works/v2beta1"
```
