### ISSUE TITLE
SA failed to patch Kubernetes objects reconciled by the Kustomization across namespaces

### ISSUE THREAD

**Issue by saeedfazal** [weaveworks/weave-gitops-enterprise#1463]
`Serviceaccount` created in a tenant namespace failed to patch Kubernetes objects reconciled by the Kustomization in `spec.targetNamespace`

**`gitops create tenant `generated SA**
```
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    toolkit.fluxcd.io/tenant: test-team
  name: test-team
  namespace: test-kustomization
```
**kustomization yaml for the tenant**
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: test-kustomization  
spec:
  interval: 30s
  path: ./kustomize
  prune: true
  serviceAccountName: test-team
  sourceRef:
    kind: GitRepository
    name: my-podinfo
  targetNamespace: test-system
```

**SA patch error**
![Screenshot 2022-09-06 at 15.47.17.png](https://images.zenhubusercontent.com/60be1f965b600cfd5b5771fb/bdae10fc-5c44-4533-af42-60e9a84cd577)
