### ISSUE TITLE
'Add an application' generate kustomizations on a non-reconcilable path

### ISSUE THREAD

**Issue by saeedfazal** [weaveworks/weave-gitops-enterprise#1475]
**Example:** Adding application in management cluster always adds kustomization files to `<git-repo>/clusters/management` default repository path.  In case user sets the repositoryPath to a different path, then the `management` directory created by `Add Application` is not on flux reconciliation path, which user needs to add manually so that application reconciliation happen.

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: clusters-app-kustomization
  namespace: flux-system
spec:
  interval: 10m0s
  path: clusters/management
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

```
