### ISSUE TITLE
Adding kustomization/application using Gitrepository source fails

### ISSUE THREAD

**Issue by saeedfazal** [weaveworks/weave-gitops-enterprise#1476]
Adding kustomization using `GitRepository` source fails because the generated kustomization yaml for application is missing `targetNamespace` for the deployment.

_NB: HelmRelease application creation/reconciliation works without any issue._ 

**Example:**

1. Add `Gitrepository` source to the management cluster.
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: my-podinfo
  namespace: test-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
```

2. Add an application via dashboard.
![Screenshot 2022-09-08 at 16.31.04.png](https://images.zenhubusercontent.com/60be1f965b600cfd5b5771fb/5ebbe669-5ebe-4745-941f-eb71e98b3a89)

3. Merge the PR and reconcile the generated kustomiztion yaml.
4. The generated kustomiztion looks like this:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-podinfo
    namespace: test-system
status: {}
```
5. The reconciliation fails with the following error:
![Screenshot 2022-09-08 at 16.35.21.png](https://images.zenhubusercontent.com/60be1f965b600cfd5b5771fb/6a24e52b-78ac-4b21-aa87-9b29e5317946)
