### ISSUE TITLE
gitops create tenants does not support OCIRepository repository types

### ISSUE THREAD

**Issue by saeedfazal** [weaveworks/weave-gitops-enterprise#1489]
**OCIRepository** repository type is not supported  for `allowedRepositories`.

```
- name: test-team
    namespaces:
    - test-system
    allowedRepositories:
    - kind: GitRepository
      url: https://github.com/stefanprodan/podinfo
    - kind: OCIRepository
      url: iad.ocir.io/ansh81vru1zp/project01/acme-web-app:version2.0.test
```

```
Error: failed to generate tenant output: 1 error occurred:
	* invalid repository kind: OCIRepository
```
