### ISSUE TITLE
Pipeline details API endpoint does not return the correct namespace

### ISSUE THREAD

**Issue by yiannistri** [weaveworks/weave-gitops-enterprise#1522]
Using the following pipeline CR

```
apiVersion: pipelines.weave.works/v1alpha1
kind: Pipeline
metadata:
  name: podinfo
  namespace: default
spec:
  appRef:
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: podinfo
  environments:
    - name: dev
      targets:
        - namespace: dev-01
          clusterRef:
            kind: GitopsCluster
            name: leaf-01
            namespace: flux-system
    - name: prod
      targets:
        - namespace: prod
          clusterRef:
            kind: GitopsCluster
            name: leaf-01
            namespace: flux-system
```
I get the following response back
```
{
  "pipeline": {
    "name": "podinfo",
    "namespace": "default",
    "appRef": {
      "apiVersion": "helm.toolkit.fluxcd.io/v2beta1",
      "kind": "HelmRelease",
      "name": "podinfo"
    },
    "environments": [
      {
        "name": "dev",
        "targets": [
          {
            "namespace": "dev-01",
            "clusterRef": {
              "kind": "GitopsCluster",
              "name": "leaf-01"
            }
          }
        ]
      },
      {
        "name": "prod",
        "targets": [
          {
            "namespace": "prod",
            "clusterRef": {
              "kind": "GitopsCluster",
              "name": "leaf-01"
            }
          }
        ]
      }
    ],
    "targets": [],
    "status": {
      "environments": {
        "dev": {
          "targetsStatuses": [
            {
              "clusterRef": {
                "kind": "GitopsCluster",
                "name": "leaf-01"
              },
              "namespace": "default",
              "workloads": [
                {
                  "kind": "HelmRelease",
                  "name": "podinfo",
                  "version": "6.1.8"
                }
              ]
            }
          ]
        },
        "prod": {
          "targetsStatuses": [
            {
              "clusterRef": {
                "kind": "GitopsCluster",
                "name": "leaf-01"
              },
              "namespace": "default",
              "workloads": [
                {
                  "kind": "HelmRelease",
                  "name": "podinfo",
                  "version": "6.2.0"
                }
              ]
            }
          ]
        }
      }
    }
  }
}
```

As you'll notice the namespaces returned in "status" are set to "default" which is incorrect.
