### ISSUE TITLE
Ensure the UI renders the environments/targets in order

### ISSUE THREAD

**Issue by yiannistri** [weaveworks/weave-gitops-enterprise#1547]
For example, given this pipeline:

```
apiVersion: pipelines.weave.works/v1alpha1
kind: Pipeline
metadata:
  name: podinfo-02
  namespace: default
spec:
  appRef:
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: podinfo
  environments:
    - name: dev
      targets:
        - namespace: podinfo-02-dev
          clusterRef:
            kind: GitopsCluster
            name: dev
            namespace: flux-system
    - name: test
      targets:
        - namespace: podinfo-02-qa
          clusterRef:
            kind: GitopsCluster
            name: dev
            namespace: flux-system
        - namespace: podinfo-02-perf
          clusterRef:
            kind: GitopsCluster
            name: dev
            namespace: flux-system
    - name: prod
      targets:
        - namespace: podinfo-02-prod
          clusterRef:
            kind: GitopsCluster
            name: prod
            namespace: flux-system
```

the order of environments shown should be: `dev` `test` `prod`
and for `test` environment the order of targets shown should be: `dev/podinfo-02-qa` `dev/podinfo-02-perf`

https://gitops.internal-dev.wego-gke.weave.works/applications/pipelines/details?namespace=default&name=podinfo-02
