### ISSUE TITLE
Improve "bad template" error messages

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#156]
@LutzLange found a good one:

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: AWSManagedMachinePool
    metadata:
      name: "${CLUSTER-NAME}-pool-0"
      namespace: default
    spec: {}
```

Errors but is very hard to see. Maybe we can also print info about the "object" in the resources list that had the issue?
