### ISSUE TITLE
Allow writing templates resources to different paths

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#1573]
Possible new `resourcetemplates` formats

### Retain the list of objects: ( This is the approach we will go with)

```yaml
  resourcetemplates:
    - path: "./clusters/{{ .params.NAMESPACE }}/{{ .params.CLUSTER_NAME }}/bases-kustomization.yaml"
      content:
      - apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
        kind: Kustomization
        metadata:
          name: clusters-bases-kustomization
          namespace: flux-system
        spec:
          path: clusters/bases/rbac
        ...

    - path: "./clusters/management/clusters/{{ .params.NAMESPACE }}/{{ .params.CLUSTER_NAME }}.yaml"
      content: 
      - apiVersion: gitops.weave.works/v1alpha1
        kind: GitopsCluster
        metadata:
          name: {{ .params.CLUSTER_NAME }}
        ...

      - apiVersion: cluster.x-k8s.io/v1beta1
        kind: Cluster
        metadata:
          name: {{ .params.CLUSTER_NAME }}
        ...
```

## Work involved

We want to keep things backwards compatible or at least a very smooth migration.

- Updating the CRD definition with a new key `resourceTemplateDefinitions`
- Updating the BE to use it

## Work not involved for now

- UI, it will stay the same
- TBD: UI work to maybe show the paths in the future.

### filenames as keys

```yaml
resourcetemplates:
  "./clusters/{{ .params.NAMESPACE }}/{{ .params.CLUSTER_NAME }}/bases-kustomization.yaml":
    - apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        name: clusters-bases-kustomization
        namespace: flux-system
      spec:
        interval: 10m0s
        path: clusters/bases/rbac
      ...

  "./clusters/management/clusters/{{ .params.NAMESPACE }}/{{ .params.CLUSTER_NAME }}.yaml":
    - apiVersion: gitops.weave.works/v1alpha1
      kind: GitopsCluster
      ...

    - apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      ...
```

OR

### like `ConfigMap` keyValues with file blobs

- doesn't have to be yaml anymore, could be JSON.. values.yaml.. 

```yaml
  resourcetemplates:
    "./clusters/{{ .params.NAMESPACE }}/{{ .params.CLUSTER_NAME }}/bases-kustomization.yaml": |
      ---
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        name: clusters-bases-kustomization
        namespace: flux-system
      spec:
        interval: 10m0s
        path: clusters/bases/rbac
    "./clusters/management/clusters/{{ .params.NAMESPACE }}/{{ .params.CLUSTER_NAME }}.yaml": |
      ---
      apiVersion: gitops.weave.works/v1alpha1
      kind: GitopsCluster
      ...
      ---
      apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      ...
```

As they are today:

```yaml
apiVersion: capi.weave.works/v1alpha1
kind: CAPITemplate
metadata:
  name: cluster-template-development
  namespace: default
spec:
  description: A simple CAPD template
  renderType: templating
  params:
    - name: CLUSTER_NAME
      required: true
      description: This is used for the cluster naming.
    - name: NAMESPACE
      description: Namespace to create the cluster in
      default: default
    - name: KUBERNETES_VERSION
      description: Kubernetes version to use for the cluster
      options: ["1.19.11", "1.21.1", "1.22.0", "1.23.3"]
      default: "1.23.3"
  resourcetemplates:
    - apiVersion: gitops.weave.works/v1alpha1
      kind: GitopsCluster
      metadata:
        name: "{{ .params.CLUSTER_NAME }}"
        namespace: "{{ .params.NAMESPACE }}"
        labels:
          weave.works/capi: bootstrap
          weave.works/cluster-name-upper: "{{ .params.CLUSTER_NAME | upper }}"
      spec:
        capiClusterRef:
          name: "{{ .params.CLUSTER_NAME }}"
    - apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      metadata:
        name: "{{ .params.CLUSTER_NAME }}"
        namespace: "{{ .params.NAMESPACE }}"
        labels:
          cni: calico
      spec:
        clusterNetwork:
          pods:
            cidrBlocks:
              - 192.168.0.0/16
          serviceDomain: cluster.local
          services:
            cidrBlocks:
              - 10.128.0.0/12
        controlPlaneRef:
          apiVersion: controlplane.cluster.x-k8s.io/v1beta1
          kind: KubeadmControlPlane
          name: "{{ .params.CLUSTER_NAME }}-control-plane"
          namespace: "{{ .params.NAMESPACE }}"
        infrastructureRef:
          apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
          kind: DockerCluster
          name: "{{ .params.CLUSTER_NAME }}"
          namespace: "{{ .params.NAMESPACE }}"
```
