### ISSUE TITLE
Error when trying to Open the Application Violations Details page

### ISSUE THREAD

**Issue by taghreed86** [weaveworks/weave-gitops-enterprise#1574]
**Priority**
 - high

**Describe the bug**
I have violations on my applications and those violations appeared in the Violations List normally but when trying to open any application violation details page I got an error as in the below screen shot
![app violations details error.png](https://images.zenhubusercontent.com/62d6d1878b9020122c2c6e2d/e8ecee68-4b16-4991-877d-e8fcf9105703)

**Precondtions**
Just follow these steps to connect cluster and create Apps then generate violations for these apps
1- first you need to connect to the testing cluster, so put the following code into file for example test-cluster.yaml
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EZ3hOakUxTURVME9Gb1hEVE15TURneE16RTFNRFUwT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWcvCkNFZzQvejhjK1R5YlE3YjF3TU1zV0NENWp6UytTeFNGMFhUcXc4TUJXNWgyQytEbVI0cmdhU3FDdHJCQW41ZysKeVRVd1pXdkplcXpsWU1LblJSbUNKOENwSWVhTE5vQXRJelFEMWEzYVRuSGZDc08zYXA5QmVGOXRZditvZVh0WgpvOVR6aSt0Q1Vwc2Q4VXljcVBiUWU5WDlab1F5RGxabi9iUnI3ZzdIeXJyWlZwRDJSUk1qd0NDMkhzR05KdE9tCnZRUGJDb21WTWFaRGo0a3gyWUxxdlJjR05pRFZWUVQvSEZERkVsaS8vSXpCemFOc1ZYbHlTbE43ekpnd2p3ZEoKbE9CdVM1eE5VRFVBN2JxWEUvaE51blVETER5NG1xNFVyckM1U2ZHVTBXbnFUblJ0RzE5amRFUkUwNWpXdkt3dwpMdWd0LzZFdjRZT1Z3NW80M3VzQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZLbXIzeGwzMEFiK3Z3T2VyNVpab2pGZlRESFBNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBM3BDdGFiQXk4VWQ3Q3BVRW1NWXhXN25sWFhHNERrQTZYOTZ0VCtuYU5SQ242U05TQgowNHBDV2I1VEVXMkdoaHRxZGh0eXFUazNhZk1FWDlNSDFPZkFXNkozRno0MDlEenBrRDBHbi8wdnp3VXNFWDJ0ClFoY0pnOVlEMHJ6R3NENFpVZkRoWmFOYTVDQW5hcFVTdVQ0bDJNZ2JZUmxXSFBLV0c0WU1sdXYzR3dyeStFRWgKMG1GSTNVVm5CQ25EMTF0d0dVaENoUFRnV3U0V0U0M1JQRGwwa3dnaUJkMWhEdU9iVU1DNGZhNThXVjgremRuQQppWE5vL3Q4RUpjaEZFOFRSNk5wODFSUWVzVHVhcmtmNU1LakliTm5hcGY4bjZJSU5WOGJoUCtpeEtnNHlLZW1wCkxGdmJ6Q2hBNmtMSzNaU01RR2NrZEcrb3hDTlZhZEZSUEdvZAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://BF8851623558E0E72C52B4086618661C.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:702231660698:cluster/policy-test
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:702231660698:cluster/policy-test
    namespace: default
    user: mgxdevteam-default-arn:aws:eks:us-east-1:702231660698:cluster/policy-test
  name: mgxdevteam-default-arn:aws:eks:us-east-1:702231660698:cluster/policy-test
current-context: mgxdevteam-default-arn:aws:eks:us-east-1:702231660698:cluster/policy-test
kind: Config
preferences: {}
users:
- name: mgxdevteam-default-arn:aws:eks:us-east-1:702231660698:cluster/policy-test
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ikd3MmxTenRnakR6elNwdHh5RzFMdkxna28ySmgwNl9yN0doUDZLQzdvRFkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6Im1neGRldnRlYW0tdG9rZW4tbTc2Y3YiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibWd4ZGV2dGVhbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImRlMjQ4M2NmLTRkYTAtNDA1ZC1hYTEwLTFhM2NmNzQwNDU2ZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0Om1neGRldnRlYW0ifQ.Jivkm5cvuhLJEMtZ71ogmEANnw0G6tQM6ZnJV2csUhM2rLIy3SE3X050yEaVbMV3MfikbbvAzRX_qaA6wP-sm-HIDoSTJp9JHPhVTrTB42rir9YnGC97NHbAaHnmYu9ZysLXWpXsXs4xDiDSlPyQKvExrk2NdncHH7wgoB9_VjmFeFli5pGlmQ18rUX4difEVDrMgV77gqmJEytcQsikm4t2piHNbfGpeLPxVNPV7T-arcU_6VjJ3_ZuZ6RdPd7UDBx3FiqwfC2EgVr6gyFrN1wQeXZ4PvvyQ3cvOAanb854VHJ4tj1WjmoWsTQ2anpfNEzznJqQ8NoPFLw6tswaVw
```

2. now you can be able to use kubectl command on that cluster
`export KUBECONFIG=test-cluster.yaml
kubectl get po`

3. clone this repository
`https://github.com/ahsayde/gitops-apps`

4.  to generate violations for my-service-1 app run
`kubectl apply -f gitops-apps/my-service-1/helm/templates/deployment.yaml`

5. to generate violations for my-service-2 app run
`kubectl apply -f gitops-apps/my-service-2/helm/templates/deployment.yaml`

**To Reproduce**

1. Login to https://demo-01.wge.dev.weave.works/
2. Press "**Applications**"  from the side navigation bar
3. press **"my-service-2"** application from the list
4. Open "**Violations**" tab
5. press the any violation in the list to see its **Details**

**Expected behavior**
Application Violation **Details** page open normally
