### ISSUE TITLE
[UI] Add "Edit" button to all details page if they have a "create-request" annotation

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#1591]
This PR intro'd choosing which of your `resourcetemplates` should receive the "initial-create-request" annotation which stores all the params that were used to render the template.

https://github.com/weaveworks/weave-gitops-enterprise/pull/1585

E.g. how it works for clusters:

https://github.com/wkp-example-org/capd-demo-reloaded/blob/main/clusters/management/clusters/default/testwithapps01.09.yaml

```yaml
apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  annotations:
    templates.weave.works/create-request: '{"head_branch":"create-clusters-branch-tutepl","title":"Creates
      cluster testwithapps01.09","description":"This PR creates a new cluster","template_name":"cluster-template-development","parameter_values":{"CLUSTER_NAME":"testwithapps01.09","CONTROL_PLANE_MACHINE_COUNT":"1","KUBERNETES_VERSION":"1.23.3","NAMESPACE":"default","WORKER_MACHINE_COUNT":"1","branchName":"create-clusters-branch-tutepl","commitMessage":"Creates
      capi cluster","provider":"GitHub","pullRequestDescription":"This PR creates
      a new cluster","pullRequestTitle":"Creates cluster testwithapps01.09","url":"https://github.com/wkp-example-org/capd-demo-reloaded"},"commit_message":"Creates
      capi cluster","credentials":{},"kustomizations":[{"metadata":{"name":"a001","namespace":"flux-system"},"spec":{"path":"./cert-manager","source_ref":{"name":"flux-system","namespace":"flux-system"}}},{"metadata":{"name":"a002","namespace":"flux-system"},"spec":{"path":"./cert-manager","source_ref":{"name":"flux-system","namespace":"flux-system"}}}]}'
```

This annotation is applied to the _FIRST_ item in the list e.g. https://github.com/wkp-example-org/capd-demo-reloaded/blob/main/clusters/management/capi/templates/capd-template.yaml#L28-L38

It will also "complete" annotations it finds to allow the user to chose something other than the FIRST item:

```yaml
 resourcetemplates:
    - kind: Kustomization
      metadata:
        name: "{{ .params.CLUSTER_NAME }}"
        namespace: "{{ .params.NAMESPACE }}"
        annotations:
          templates.weave.works/create-request:

    - kind: HelmRepository
      metadata:
        name: "{{ .params.CLUSTER_NAME }}"
        namespace: "{{ .params.NAMESPACE }}"
        annotations:
          templates.weave.works/create-request:

```

Then both those resources will have the create-request attached and should display the EDIT button if they are rendered in the UI.
