### ISSUE TITLE
[Regression] Smoke tests are failing due to missing cni: calico label for capi cluster in PR preview

### ISSUE THREAD

**Issue by saeedfazal** [weaveworks/weave-gitops-enterprise#1651]
Smoke tests are failing because CNI lable `cni: calico` can't be found in CAPI cluster creation PR

The CAPD template snip specifying the cni:
```
 - apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      metadata:
        name: "${CLUSTER_NAME}"
        namespace: "${NAMESPACE}"
        labels:
          cni: calico
      spec:
        clusterNetwork:
          pods:
```

The PR preview snip missing `cni` label for the cluster:
```
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    templates.weave.works/template-name: cluster-template-development-0
    templates.weave.works/template-namespace: default
  name: ui-end-to-end-capd-cluster
  namespace: capi-test-system
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
```
