### ISSUE TITLE
[BE] Update render endpoint to return dummy estimatedCost

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#1679]
Rendering a template will now return a cost estimate range too.

> **Note**
> This is a "cornerstone" issue to establish the new API between UI/BE and will initially return only mock ($0) data

### Task breakdown

- [x] Add new field `costEstimateMonthlyDollars` to the response from `/v1/templates/render`
- [x] Return some dummy values by default

[0] `costEstimateMonthlyDollars`
```yaml
{
  currency: string,
  amount: number,
  range: {
    low: float,
    high: float
  }
}
```

[1] dummy data:
```
{
  currency: "USD",
  range: {
    low: 0,
    high: 1000000,
  }
}
```
