### ISSUE TITLE
[UI] A tenant can not view application deployment details

### ISSUE THREAD

**Issue by saeedfazal** [weaveworks/weave-gitops-enterprise#1684]
UI doesn't show the application deployment details for a tenant in details page.

**Tenant definition:**
```
tenants:
  - name: test-team
    namespaces:
    - test-kustomization
    - test-system
    teamRBAC:
      groupNames: 
      - wge-test
      rules:
      - apiGroups: [""]
        resources: ["secrets", "pods", "services" ]
        verbs: [ "get", "list" ]
      - apiGroups: ["apps"]
        resources: [ "deployments", "replicasets"]
        verbs: [ "get", "list" ]
      - apiGroups: ["kustomize.toolkit.fluxcd.io"]
        resources: [ "kustomizations" ]
        verbs: [ "get", "list", "patch" ]
      - apiGroups: ["helm.toolkit.fluxcd.io"]
        resources: [ "helmreleases" ]
        verbs: [ "get", "list", "patch" ]
      - apiGroups: ["source.toolkit.fluxcd.io"]
        resources: [ "buckets", "helmcharts", "gitrepositories", "helmrepositories", "ocirepositories" ]
        verbs: [ "get", "list", "patch" ] 
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["get", "watch", "list"]
      - apiGroups: ["autoscaling"]
        resources: ["horizontalpodautoscalers"]
        verbs: ["get", "watch", "list"]
      - apiGroups: ["infra.contrib.fluxcd.io"]
        resources: ["terraforms"]
        verbs: ["get", "watch", "list", "patch"]     
      - apiGroups: [""]
        resources: ["configmaps"]
        verbs: ["get", "list", "watch"]       
      - apiGroups: ["gitops.weave.works"]
        resources: ["gitopsclusters"]
        verbs: ["get", "watch", "list"]
```
**Tenant application View:**![Screenshot 2022-10-12 at 09.54.51.png](https://images.zenhubusercontent.com/60be1f965b600cfd5b5771fb/a7c1eae8-3587-4ee7-bf02-d14c3266ac54)

**Tenant detail View:**![Screenshot 2022-10-12 at 09.42.45.png](https://images.zenhubusercontent.com/60be1f965b600cfd5b5771fb/6b72e7ac-53df-4b81-b3df-d2d83ed79173)

**Admin detail view:**![Screenshot 2022-10-12 at 09.43.34.png](https://images.zenhubusercontent.com/60be1f965b600cfd5b5771fb/a00a626d-73fb-494d-9430-0cff88746cce)
