### ISSUE TITLE
Canary Template

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops-enterprise#1712]
In order to demonstrate self service capabilities within WGE, we should explore how a Canary GitOpsTemplate could look.

We have sample Canary Objects for each deployment strategy on our demo repo here: https://github.com/weaveworks/weave-gitops-clusters/tree/main/k8s/clusters/internal-dev-gke/canaries. How we determined deployment strategy could also be useful for authoring a set of templates , or - if possible, asking the user for the appropriate values based on selected strategy earlier in the form: https://github.com/weaveworks/weave-gitops-enterprise/issues/879

Also to look at:
- templating capabilities/conditions: https://pkg.go.dev/text/template
- defaults: https://docs.gitops.weave.works/docs/cluster-management/profiles/#2-select-which-profiles-you-want-installed-when-creating-a-cluster

Ultimately a Template is an example, and could be customized by the customer or provided weaveworks representative in order to better match their intended use - we could therefore make assumptions and scope to a specific use case.

Based on our examples, a lot could be made generic from a "Flagger configuration" perspective, with the user asked for Application configuration, and _potentially_ deployment strategy. This could also be improved with a set of MetricTemplates.

90% might work example :
```
apiVersion: clustertemplates.weave.works/v1alpha1
kind: GitOpsTemplate
metadata:
  name: progressive-delivery-canary
  namespace: default
  annotations: # may be able to remove following https://github.com/weaveworks/weave-gitops-enterprise/issues/1730
    templates.weave.works/profiles-enabled: false
    templates.weave.works/kustomizations-enabled: false
    templates.weave.works/credentials-enabled: false
  labels:
    weave.works/template-type: progressive-delivery #used to determine 'Type'
spec:
  description: Enable Progressive Delivery with Flagger and Istio
  params:
  #metadata
    - name: RESOURCE_NAME
      description: Name of Flagger Canary
  #Appdata
    - name: APP_NAME
      description: As specified on the target deployment label selector
    - name: APP_PORT
      description: ClusterIP port number
    - name: APP_HOST
      description: Hostname
  resourcetemplates:
  - apiVersion: flagger.app/v1beta1
    kind: Canary
    metadata:
    name: ${RESOURCE_NAME}
    spec:
      provider: istio 
      # deployment reference
      targetRef: 
        apiVersion: apps/v1
        kind: Deployment
        name: ${APP_NAME}
        autoscalerRef:
          apiVersion: autoscaling/v2
          kind: HorizontalPodAutoscaler
          name: ${APP_NAME} # assumed same for now, can be separate value
        progressDeadlineSeconds: 60 
        service: 
          # ClusterIP port number
          port: ${APP_HOST}
          # container port number or name
          targetPort: ${APP_PORT} # assumed same for now, can be separate value
          gateways:
          - istio-system/public-gateway
          hosts:
          - ${APP_HOST}
          trafficPolicy: 
          tls:
            mode: DISABLE
        analysis:
          # schedule interval (default 60s)
          interval: 1m 
          # max number of failed metric checks before rollback
          threshold: 5 
          # total number of iterations
          maxWeight: 50
          stepWeight: 10
          metrics: 
          - name: request-success-rate
            thresholdRange:
              min: 99
            interval: 1m
          - name: request-duration
            thresholdRange:
              max: 500
            interval: 30s
          webhooks: 
          - name: acceptance-test
            type: pre-rollout
            timeout: 30s
            url: http://flagger-loadtester.istio-system/
            metadata:
              type: bash
              cmd: "curl -sd 'test' http://${APP_HOST}:${APP_HOST}/token | grep token"
              logCmdOutput: "true"
          - name: load-test
            type: rollout
            timeout: 15s
            url: http://flagger-loadtester.istio-system/
            metadata:
              type: cmd
              cmd: "hey -z 5m -q 10 -c 2 http://${APP_HOST}:${APP_HOST}"
            logCmdOutput: "true"
```
