### ISSUE TITLE
Cannot show Pipeline details when namespace is missing in clusterRef

### ISSUE THREAD

**Issue by makkes** [weaveworks/weave-gitops-enterprise#1748]
**WGE release:**
 - main/4da74c12d008eed17b847d3da26ebdb3e15e11f3

**Kubernetes release:**
 - 1.24.0

**Priority**
?

**Describe the bug**
Given a Pipeline with an environment using this clusterRef:
```
apiVersion: pipelines.weave.works/v1alpha1
kind: Pipeline
metadata:
  name: metallb
  namespace: default
[...]
spec:
  environments:
  - name: dev
    targets:
    - clusterRef:
        kind: GitopsCluster
        name: dev
      namespace: flux-system
[...]
Navigating to http://localhost:8000/applications/pipelines/details?name=metallb&namespace=default reveals this error message:

```
failed getting app=metallb on cluster=/dev: cluster=/dev not found
```

**To Reproduce**
see above

**Expected behaviour**
the Pipeline details are rendered.

**Cloud provider:**
n/a

**Additional context**
Supposedly, WeGo doesn't take into account the Pipeline's Namespace if the clusterRef doesn't have a Namespace defined.
