### ISSUE TITLE
pipeline details ui does not show cluster details nor app link when cluster is management

### ISSUE THREAD

**Issue by enekofb** [weaveworks/weave-gitops-enterprise#1773]
**WGE release:**
 - Weave GitOps Enterprise 2022-10 0.10.0-rc.2-6-g2beaf26

**Priority**
 - medium

**Describe the bug**

At the back of testing https://github.com/weaveworks/weave-gitops-enterprise/issues/1711 

we have found that neither `cluster`  nor `link to the app` exists  for the deployment target card that refers to the management cluster 

https://github.com/weaveworks/weave-gitops-enterprise/pull/1756#issuecomment-1290675839

**To Reproduce**
Create a pipeline similar to the following 
```yaml
apiVersion: pipelines.weave.works/v1alpha1
kind: Pipeline
metadata:
  name: dex
  namespace: dex
spec:
  appRef:
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: dex
  environments:
    - name: dev
      targets:
        - namespace: dex
```

**Expected behaviour**

- Application link exists
- Cluster info exists with the name of the management cluster

**Cloud provider:**
 - AWS

**Additional context**
