### ISSUE TITLE
[UI] Add cluster / application / etc feature does not respect gitops flux configuration when branch and path are specified

### ISSUE THREAD

**Issue by enekofb** [weaveworks/weave-gitops-enterprise#1801]
**WGE release:**
0.9.5

**Kubernetes release:**
not relevant

**Priority**
 - medium

**Severity**
 - medium

**Describe the bug**

Add X (where X is cluster, application, etc ) not taking consistently into consideration flux configuration when pointing to a branch with a particular path. 

**Given** the following [example](https://github.com/weaveworks/clusters-config/blob/cluster-pentest-enterprise/eksctl-clusters/clusters/pentest-enterprise-eksctl-cluster.yaml#L45) where flux manifests are in a specified branch and path

```yaml 
gitops:
  flux:
    gitProvider: github
    flags:
      owner: "weaveworks"
      repository: "clusters-config"
      private: "true"
      branch: "cluster-pentest-enterprise"
      namespace: "flux-system"
      path: "eksctl-clusters/clusters/pentest-enterprise"
```

**When** created an application or a cluster 

**Then** the PR are not created respecting flux settings 
[app pr](https://github.com/weaveworks/clusters-config/pull/122/files)
[cluster pr](https://github.com/weaveworks/clusters-config/pull/120/files)

So when the PR is merged flux does not see it so another PR is required to move the manifests to the right location
https://github.com/weaveworks/clusters-config/pull/121

**To Reproduce**
as specified in the previous section

**Actual behaviour**
PR is created to a default path for some resources 

**Expected behaviour**
PR are create in the path where flux is configured

**Cloud provider:**
- AWS

**Proposed UI fix**

- UI should send the branch of the GitRepository to the CreatePullRequest endpoint instead of always sending main
