### ISSUE TITLE
[BE] Improve profile support in GitOpsTemplates and make it part of the CR

### ISSUE THREAD

**Issue by davidstauffer** [weaveworks/weave-gitops-enterprise#1815]
### Background

Profiles can be currently added as annotations to templates.
```
 annotations:
    capi.weave.works/profile-0: '{"name": "weave-policy-agent", "editable": true, "version": "0.2.8", "values": "accountId: weaveworks\nclusterId: ${CLUSTER_NAME}" }'
    capi.weave.works/profile-1: '{"name": "dex", "version": "0.0.8", "values": "accountId: weaveworks\nclusterName: ${CLUSTER_NAME}" }'
```

The original intention of that very simple approach was, that we wanted to be aligned with CAPI templating upstream.

Today we have feedback from users that the annotations are very difficult to comprehend and debug. 

### Goals

As a User, I want to easily manage the profiles and the capabilities as part of my templates so that I can provide the services I need

Proposal 1: ( By Kevin)
```
spec:
  resourceTemplates:
  - ...
  profiles:
    - name: ...
      namespace: ...
      values:
        my_value: testing
```

CC @bigkevmcd @foot
