### ISSUE TITLE
Custom delimiters doesn't work with 'templating' renderType

### ISSUE THREAD

**Issue by saeedfazal** [weaveworks/weave-gitops-enterprise#1946]
**WGE Story/Feature:**
 - GitOps templates / latest-main

**Priority**
 - medium

**Severity**
 - high

**Describe the bug**
UI doesn't render template parameters when custom delimiters are used e.g. `templates.weave.works/delimiters: "$[[,]]"`

**To Reproduce**
- Create any `GitOpsTemplate` using custom delimiters.
- Render the template in UI
```
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsTemplate
metadata:
  name: profiles-catalog-template
  namespace: default
  labels:
    weave.works/template-type: source
  annotations:
    templates.weave.works/cost-estimation-enabled: "false"
    templates.weave.works/profiles-enabled: "false"
    templates.weave.works/credentials-enabled: "false"
    templates.weave.works/kustomizations-enabled: "false"
    templates.weave.works/delimiters: "$[[,]]"
spec:
  renderType: templating
  description: A HelmRepository template
  params:
    - name: RESOURCE_NAME
      required: true
      default: weave-gitops-profile-examples
      description: Name to give the Helm Repository
    - name: NAMESPACE
      description: Namespace to create the source in
      default: default
    - name: URL
      description: URL of the helm repository
      default: https://raw.githubusercontent.com/weaveworks/profiles-catalog/gh-pages
    - name: INTERVAL
      description: How often to check for updates
      default: 30s
  resourcetemplates:
    - apiVersion: source.toolkit.fluxcd.io/v1beta1
      kind: HelmRepository
      metadata:
        name: $[[ .params.RESOURCE_NAME ]]
        namespace: $[[ .params.NAMESPACE ]]
        annotations:
          templates.weave.works/create-request: ""
      spec:
        interval: $[[ .params.INTERVAL ]]
        url: $[[ .params.URL ]]
```

**Actual behaviour**
The rendered template is missing all the template parameters.

**Expected behaviour**
The template should be rendered with template parameters.

**Test Environment**
N/A

**Additional context**
![Screenshot 2022-11-24 at 11.34.03.png](https://images.zenhubusercontent.com/60be1f965b600cfd5b5771fb/7325e86a-de0b-4487-98c8-fa77684a5da7)
