### ISSUE TITLE
Some of the supported spring library functions doesn't work with rendering type 'templating'

### ISSUE THREAD

**Issue by saeedfazal** [weaveworks/weave-gitops-enterprise#1958]
**WGE Story/Feature:**
 - GitOps Templates

**Priority**
 - high

**Severity**
 - medium

**Describe the bug**
Some of the spring library functions mentioned in the documentation doesn't work with `templating` render type. For example an important function `fromJson` doesn't work as it is useful to provide helm chart values.

**To Reproduce**
- Use the following sample template and pass the `"{\"foo\": 55}"` as values template parameter.
- Now create the PR or preview the PR
```
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsTemplate
metadata:
  name: helmrelease-template
  namespace: default
  labels:
    weave.works/template-type: application
  annotations:
    templates.weave.works/cost-estimation-enabled: "false"
    templates.weave.works/profiles-enabled: "false"
    templates.weave.works/credentials-enabled: "false"
    templates.weave.works/kustomizations-enabled: "false"
    templates.weave.works/delimiters: "${{,}}"
spec:
  renderType: templating
  description: A generic helmrelease template
  params:
    - name: RESOURCE_NAME
      required: true
      description: Name to give the kustomization
    - name: NAMESPACE
      description: Namespace to create the source in
      default: default
    - name: SOURCE_NAME
      required: true
      description: Source that contains the Kubernetes manifests
    - name: SOURCE_NAMESPACE
      required: true
      default: default
      description: Namespace of source
    - name: CHART_NAME
      required: true
      description: Helm chart name
    - name: CHART_VERSION
      required: true
      description:  Helm chart version, accepts a semver range
    - name: VALUES
      required: true
      default: "null"
      description: "A json sting containing values.yaml \"{\"name\": foo}\""
    - name: TARGET_NAMESPACE
      required: true
      default: default
      description: Namespace of all Kustomization objects
    - name: INTERVAL
      description: How often to check for updates
      default: 30s
  resourcetemplates:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: ${{ .params.RESOURCE_NAME }}
        namespace: ${{ .params.NAMESPACE }}
      spec:
        interval: 30s
        chart:
          spec:
            chart: ${{ .params.CHART_NAME }}
            sourceRef:
              apiVersion: source.toolkit.fluxcd.io/v1beta2
              kind: HelmRepository
              name: ${{ .params.SOURCE_NAME }}
              namespace:  ${{ .params.SOURCE_NAMESPACE }}
            version: ${{ .params.CHART_VERSION }}
        targetNamespace: ${{ .params.TARGET_NAMESPACE }}
        values: ${{ .params.VALUES | fromJson }} 
```
**Actual behaviour**
An error occurred saying function `fromJson` not defined. The error also refers to `capiTemplate` but actually it is a `gitopsTemplate`.

**Expected behaviour**
- The passed json string should be decoded and set as values

**Test Environment**
N/A

**Additional context**
![Screenshot 2022-11-28 at 11.01.00.png](https://images.zenhubusercontent.com/60be1f965b600cfd5b5771fb/aa3fe4a2-0f50-463a-aadb-74cab7774d37)
