### ISSUE TITLE
GitOpsTemplates PR review shows incorrect resource labels

### ISSUE THREAD

**Issue by saeedfazal** [weaveworks/weave-gitops-enterprise#1961]
**WGE Story/Feature:**
 - GitOps Templates

**Priority**
 - high

**Severity**
 - medium

**Describe the bug**
- The PR review always says `Cluster Definition` for created resources irrespective of the resource. 
- `Profiles` and `Kustomizations` tabs in PR review are only valid for CAPI cluster creation.

**To Reproduce**
- Preview the PR from `Create resource` page for any `non-cluster` resource e.g. source.
```
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsTemplate
metadata:
  name: git-repository-template
  namespace: default
  labels:
    weave.works/template-type: source
  annotations:
    templates.weave.works/cost-estimation-enabled: "false"
    templates.weave.works/profiles-enabled: "false"
    templates.weave.works/credentials-enabled: "false"
    templates.weave.works/kustomizations-enabled: "false"
    templates.weave.works/delimiters: "${{,}}"
spec:
  renderType: templating
  description: A GitRepository template
  params:
    - name: RESOURCE_NAME
      required: true
      description: Name to give the git repository
    - name: NAMESPACE
      description: Namespace to create the source in
      default: default
    - name: BRANCH
      description: Git repository branch name
      default: master
    - name: URL
      description: URL of the git repository
      default: https://github.com/stefanprodan/podinfo
    - name: INTERVAL
      description: How often to check for updates
      default: 30s
  resourcetemplates:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: GitRepository
      metadata:
        name: ${{ .params.RESOURCE_NAME }}
        namespace: ${{ .params.NAMESPACE }}
        annotations:
          templates.weave.works/create-request: ""
      spec:
        interval: ${{ .params.INTERVAL }}
        ref:
          branch: ${{ .params.BRANCH }}
        url: ${{ .params.URL }}
```

**Actual behaviour**
In preview the resource is labeled/shown as `Cluster Definition`.

**Expected behaviour**
- The label should not be hardcoded. A more generic label e.g. `Resource Definition` is better.
- `Profile` and `Kustomization` tabs should not be visible for standard resource templates.

**Test Environment**
N/A

**Additional context**
![Screenshot 2022-11-28 at 13.29.56.png](https://images.zenhubusercontent.com/60be1f965b600cfd5b5771fb/8d07c3b2-8840-48bd-b6d2-769463c4f90a)
