### ISSUE TITLE
[docs] GitOpsTemplate can not be used without `CLUSTER_NAME' or 'RESOURCE_NAME' template parameter.

### ISSUE THREAD

**Issue by saeedfazal** [weaveworks/weave-gitops-enterprise#1964]
**WGE Story/Feature:**
 - GitOps Template

**Priority**
 - high

**Severity**
 - medium

**Describe the bug**
No resource can be created until one of the GitOpsTemplate parameter is named either `CLUSTER_NAME` or `RESOURCE_NAME`. GitOpsTemplates are generic and should not be restricted to use specific parameter names.

**To Reproduce**
- Create a resource using following GitOpsTemplate.
```
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsTemplate
metadata:
  name: kustomization-template
  namespace: default
  labels:
    weave.works/template-type: application
  annotations:
    templates.weave.works/cost-estimation-enabled: "false"
    templates.weave.works/profiles-enabled: "false"
    templates.weave.works/credentials-enabled: "false"
    templates.weave.works/kustomizations-enabled: "false"
    templates.weave.works/delimiters: "${{,}}"
spec:
  renderType: templating
  description: This is a simple template for deploying from a git repository using a Flux Kustomization
  params:
    - name: SOURCE_NAME
      required: true
      description: Source that contains the Kubernetes manifests
    - name: NAMESPACE
      description: Namespace to create the source in
      default: default
    - name: BRANCH
      description: Git repository branch name
      default: master
    - name: URL
      description: URL of the git repository
      default: https://github.com/stefanprodan/podinfo
    - name: INTERVAL
      description: How often to check for updates
      default: 30s
  resourcetemplates:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: GitRepository
      metadata:
        name: ${{ .params.SOURCE_NAME }}
        namespace: ${{ .params.NAMESPACE }}
        annotations:
          templates.weave.works/create-request: ""
      spec:
        interval: ${{ .params.INTERVAL }}
        ref:
          branch: ${{ .params.BRANCH }}
        url: ${{ .params.URL }}
```

**Actual behaviour**
An error occurred saying:
`unable to find 'CLUSTER_NAME' or 'RESOURCE_NAME' parameter in supplied values`. 

**Expected behaviour**
Kubernetese resources should be created irrespective of the template parameters naming convention.

**Test Environment**
N/A

**Additional context**
![Screenshot 2022-11-28 at 15.30.16.png](https://images.zenhubusercontent.com/60be1f965b600cfd5b5771fb/7fe544e0-5b85-4c60-84f7-069b65f59d97)
