### ISSUE TITLE
GitOpsTemplates optional parameters still enforced

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops-enterprise#2020]
Given the below in a template:

```
params:
   - name: SECRET_REF
      description: Required credentials for HMAC PROVIDER_TYPE
      required: false
...
resourcetemplates:
  - apiVersion: notification.toolkit.fluxcd.io/v1beta1
...
    spec:
      secretRef: ${SECRET_REF}
```

I'm still getting this error on preview PR and unable to add
<img width="422" alt="Screenshot 2022-12-06 at 14 28 22" src="https://user-images.githubusercontent.com/19860021/205939149-7d3cc513-cc02-4262-b621-b33a4bc3175c.png">
