### ISSUE TITLE
GitOpsTemplate rendering errors refers to 'capi-template' in error messages

### ISSUE THREAD

**Issue by saeedfazal** [weaveworks/weave-gitops-enterprise#2080]
**WGE Story/Feature:**
 - GitOps Templates

**Priority**
 - medium

**Severity**
 - medium

**Describe the bug**
GitOpsTemplate preview/PR shows error messages referring to `capi-template`.

**To Reproduce**
- Install any GitopsTemplate with some errors in it
- Populate the template with all required parameters
- Create the `PR` or just do `PR Preview`

**Actual behaviour**
An error message should appear explaining the error related to GitOpsTemplate error.

**Expected behaviour**
An error message should refer to the error related to GitOpsTemplate error.

**Test Environment**
N/A

**Additional context**
apiVersion: templates.weave.works/v1alpha1
```
kind: GitOpsTemplate
metadata:
  name: git-kustomization-template
  namespace: test-system
  labels:
    weave.works/template-type: application
  annotations:
    templates.weave.works/cost-estimation-enabled: "false"
    templates.weave.works/profiles-enabled: "false"
    templates.weave.works/credentials-enabled: "false"
    templates.weave.works/kustomizations-enabled: "false"
    templates.weave.works/delimiters: "$[[,]]"
spec:
  renderType: templating
  description: A generic git Kustomization template for deploying from a git repository using a Flux Kustomization
  params:
    - name: RESOURCE_NAME
      required: true
      description: Name to give the kustomization
    - name: NAMESPACE
      description: Namespace to create the source in
      default: default
    - name: PATH
      required: false
      description: path to the directory containing a kustomization.yaml
    - name: SOURCE_NAME
      required: true
      description: Source that contains the Kubernetes manifests
    - name: SOURCE_NAMESPACE
      required: true
      default: default
      description: Namespace of source
    - name: TARGET_NAMESPACE
      required: true
      default: default
      description: Namespace of all Kustomization objects
    - name: PRUNE
      description: Enable garbage collection
      default: "true"
    - name: INTERVAL
      description: How often to check for updates
      default: 30s
    - name: DESCRIPTION
      description: Annotated description for the Kustomization resource
      required: false
  resourcetemplates:
    - apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        name: $[[ .params.RESOURCE_NAME ]]
        namespace: $[[ .params.NAMESPACE ]]
        annotations:
          metadata.weave.works/description: |
            $[[ .params.DESCRIPTION | b64enc ]]
      spec:
        interval: 30s
        path: $[[ .params.PATH | empty |  ternary "./" ]]
        prune: true
        sourceRef:
          kind: GitRepository
          name: $[[ .params.SOURCE_NAME ]]
          namespace:  $[[ .params.SOURCE_NAMESPACE ]]
        targetNamespace: $[[ .params.TARGET_NAMESPACE ]]
        prune: $[[ .params.PRUNE ]]
```

![Screenshot 2022-12-14 at 09.54.26.png](https://images.zenhubusercontent.com/60be1f965b600cfd5b5771fb/0598c8a8-3833-42b8-ae6b-a9cdebcb1858)
