### ISSUE TITLE
Path support for profiles

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#2107]
#1702 introduces a new pattern allowing you to specify where files in the template should go:

### Template paths

```yaml
resourcetemplates:
  - path: ./clusters/management/${{ .params.CLUSTER_NAME }}/cluster.yaml
    content:
    - kind: GitopsCluster
      metadata: ..
    - kind: Cluster
      metdata: 
  - path: ./dashboards/${{ .params.CLUSTER_NAME }}.yaml
    content:
    - kind: Dashboard
      metadata: ..
```

### New stuff

We want something similar for charts/profiles. Will look like this:
```yaml
charts:
  items:
    - chart: cert-manager
      template:
        path: ./clusters/${{ .params.CLUSTER_NAME }}/cert-manager.yaml
    - chart: policy-agent
      template:
        path: ./clusters/${{ .params.CLUSTER_NAME }}/other-profiles.yaml
    - chart: prometheus
      template:
        path: ./clusters/${{ .params.CLUSTER_NAME }}/other-profiles.yaml
    - chart: podinfo
    - chart: nginx-ingress

```

Given `CLUSTER_NAME=dev-cluster`, three profile files will be written out:
1. `./clusters/dev-cluster/cert-manager.yaml` containing:
    - `HelmRelease.cert-manager`
3. `./clusters/dev-cluster/other-profiles.yaml` containing 
    - `HelmRelease.policy-agent` 
    - `HelmRelease.prometheus`
6. `./clusters/dev-cluster/profiles.yaml` ("default") containing 
    - `HelmRelease.podinfo`
    - `HelmRelease.nginx-ingress`
    - `HelmRepository.weaveworks-charts`

if a `helmRepositoryTemplate.path` is also specified the HelmRepository will be written there instead:

```yaml
spec:
  charts:
    helmRepositoryTemplate:
      path: ./clusters/${{ .params.CLUSTER_NAME }}/profile-repositories.yaml
```

### Tasks

Update CRDs 
- Update the [ChartSpec](https://github.com/weaveworks/templates-controller/blob/main/apis/core/templates.go#L75) in the templates controller with the new keys:
  - spec.charts.items.template.path
  - spec.charts.helmRepositoryTemplate.path
- Regenerate all the CRDs/manifests with `make ??`
- Release templates-controller
- Update the helm-chart in wge w/ `make helm` from the templates-controller directory

Update logic:
- Update the renderering logic in WGE to use the path if its present, otherwise follow existing behaviour of guessing the path.
