### ISSUE TITLE
[BE] UI doesn't render the template parameter defined for resource templates path

### ISSUE THREAD

**Issue by saeedfazal** [weaveworks/weave-gitops-enterprise#2161]
**WGE Story/Feature:**
 - GitOps Template

**Priority**
 - high

**Severity**
 - medium

**Describe the bug**
UI doesn't render the template parameter defined for `resourcetemplates` path. This will make it impossible to specify user defined repository paths. UI only renders the template path parameter if it also exists in `content` body/section for the `resourcetemplates`.

**To Reproduce**
- Install the following template
```
apiVersion: templates.weave.works/v1alpha2
kind: GitOpsTemplate
metadata:
  name: helm-repository-template
  namespace: dev-system
  labels:
    weave.works/template-type: source
  annotations:
    templates.weave.works/cost-estimation-enabled: "false"
    templates.weave.works/profiles-enabled: "false"
    templates.weave.works/credentials-enabled: "false"
    templates.weave.works/kustomizations-enabled: "false"
    templates.weave.works/delimiters: "$[[,]]"
spec:
  renderType: templating
  description: A HelmRepository template
  params:
    - name: RESOURCE_NAME
      required: true
      default: bitnami
      description: Name to give the Helm Repository
    - name: NAMESPACE
      description: Namespace to create the source in
      default: default
    - name: URL
      description: URL of the helm repository
      default: https://charts.bitnami.com/bitnami
    - name: INTERVAL
      description: How often to check for updates
      default: 30s
  resourcetemplates:
    - path: "${{ .params.CLUSTER_PATH }}/${{ .params.NAMESPACE }}/${{ .params.RESOURCE_NAME }}.yaml"
      content:
        - apiVersion: source.toolkit.fluxcd.io/v1beta1
          kind: HelmRepository
          metadata:
            name: $[[ .params.RESOURCE_NAME ]]
            namespace: $[[ .params.NAMESPACE ]]
            annotations:
              templates.weave.works/create-request: ""
          spec:
            interval: $[[ .params.INTERVAL ]]
            url: $[[ .params.URL ]]
```

**Actual behaviour**
`${{ .params.CLUSTER_PATH }}` parameter is not rendered in UI.

**Expected behaviour**
`${{ .params.CLUSTER_PATH }}` should be rendered in the UI irrespective of it is used in `content` section of the `resourcetemplates`.

**Test Environment**
N/A
