### ISSUE TITLE
`gitops create template` should have `--outputPath` option

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#2215]
At the moment 

```
gitops create template capd-capi-template.yaml --values CLUSTER_NAME=ewq --export 
```

or for dev'ing:

`go run cmd/gitops/main.go create template ...`

Only renders to stdout! We want to respect the filepaths returned and write out the yaml to those paths, relative to the `--outDir` flag. e.g.

```yaml
apiVersion: template.weave.works/v1alpha2
kind: GitOpsTemplate
metadata:
  name: cluster-template-development
  namespace: default
spec:
  description: A simple CAPD template
  charts:
    items:
      - chart: cert-manager
        targetNamespace: cert-manager
        version: 0.0.8
        spec:
          install:
            remediation:
              retries: 3
  resourcetemplates:
    - path: "./clusters/${CLUSTER_NAME}.yaml"
      content:
        - apiVersion: gitops.weave.works/v1alpha1
          kind: GitopsCluster
          metadata:
            name: "${CLUSTER_NAME}"
            labels:
              weave.works/capi: bootstrap
          spec:
            capiClusterRef:
              name: "${CLUSTER_NAME}"
```

`gitops create template --outDir ./out --values CLUSTER_NAME=foo` should write out:
- ./out/clusters/foo.yaml

Resources

- https://gobyexample.com/writing-files
