### ISSUE TITLE
`gitops create template` requires you to type too many params

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#2227]
e.g.

```
gitops create template capd-capi-template.yaml --values CLUSTER_NAME=ewq,FOO=foo,BAR=bar
```

We could easily use viper to read all the params from a config file instead, e.g.

```
gitops create template --config capd-capi-template-config.yaml
```

Given `capd-capi-template-config.yaml`
```yaml
template-name: capd-capi-template.yaml
values:
  - CLUSTER_NAME=ewq
  - FOO=foo
  - BAR=bar
output-dir: ./clusters/management/clusters/
```
