### ISSUE TITLE
pipeline details and yaml view not showing for a valid pipeline depending on non existing cluster

### ISSUE THREAD

**Issue by enekofb** [weaveworks/weave-gitops-enterprise#2255]
**WGE release:**
https://github.com/weaveworks/weave-gitops-enterprise/releases/tag/v0.15.0-rc.2
**Priority**
 - medium

**Severity**
 - medium

**Describe the bug**
I have created a pipeline from a template using dummy values (see example)

The pipeline list shows fine 
I click in the pipeline details view and i get the following blank 

<img width="1537" alt="pipeline-first" src="https://user-images.githubusercontent.com/12957664/213503951-4daaed83-fa4d-4d1c-b19e-01c4b46accdb.png">

When i then refresh i could see the error
<img width="1528" alt="pipeline-second" src="https://user-images.githubusercontent.com/12957664/213503977-d439daef-a8d3-42a2-8d3f-d63dffea8e51.png">

When i go to yaml tab i cannot see the yaml
<img width="1517" alt="pipeline-third" src="https://user-images.githubusercontent.com/12957664/213504001-eda40781-ec9a-414a-ba3a-50d1a03ad674.png">

**To Reproduce**
Create the pipeline attached
Go to pipeline details view 
See that status is not showing
See that yaml tab is not showing

**Actual behaviour**
A clear and concise description of the resulting behaviour.

**Expected behaviour**
- Error message shown with the error
- I could go to yaml tab and see the manifest

**Additional context**
```yaml
apiVersion: pipelines.weave.works/v1alpha1
kind: Pipeline
metadata:
  annotations:
    templates.weave.works/create-request: '{"repository_url":"https://github.com/enekofb/wge-dev","head_branch":"wge-create-branch-nh722s","title":"Creates
      resource podinfo-soft","description":"This PR creates a pipeline-tenancy-by-namespace
      instance","template_name":"pipeline-tenancy-by-namespace","parameter_values":{"APP_NAME":"podinfo","APP_NAMESPACE":"search","APP_REPO_BRANCH":"main","APP_REPO_TYPE":"github","APP_REPO_URL":"https://www.github.com","GIT_CREDENTIALS_SECRET":"github-creds","RESOURCE_NAME":"podinfo-soft","RESOURCE_NAMESPACE":"search"},"commit_message":"Creates
      pipeline-tenancy-by-namespace instance","credentials":{},"template_namespace":"flux-system","template_kind":"GitOpsTemplate"}'
  labels:
    templates.weave.works/template-name: pipeline-tenancy-by-namespace
    templates.weave.works/template-namespace: default
  name: podinfo-soft
  namespace: search
spec:
  appRef:
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: podinfo
  environments:
  - name: dev
    targets:
    - clusterRef:
        kind: GitopsCluster
        name: dev
        namespace: flux-system
      namespace: search
  - name: test
    targets:
    - clusterRef:
        kind: GitopsCluster
        name: test
        namespace: flux-system
      namespace: search
  - name: prod
    targets:
    - clusterRef:
        kind: GitopsCluster
        name: prod
        namespace: flux-system
      namespace: search
  promotion:
    strategy:
      pull-request:
        branch: main
        secretRef:
          name: github-creds
        type: github
        url: https://www.github.com

```
