### ISSUE TITLE
Pull request generator - Optionally include forks

### ISSUE THREAD

**Issue by ranatrk** [weaveworks/weave-gitops-enterprise#2309]
Include additional fields from the PR like forks 
- Add optional flag to include forks 

Work
- Check if github/gitlab/go-scm/bitbucket support filtering PRs by fork (?) (unlikely)
- If not do a similar client-side filter of the results as we do with labels right now (probable)
- include `fork: true|false` in the template params

```yaml
pullRequests:
  labels: ["foo"]
  forks: true|false # whether to filter by them or not
```
