### ISSUE TITLE
Slightly more exposure than RBAC should allow - can list clusters

### ISSUE THREAD

**Issue by kingdonb** [weaveworks/weave-gitops-enterprise#2406]
**WGE release:** 0.17.0

**Kubernetes release:**

**Priority**
 - low
 - medium
 - high

**Severity**
 - low
 - medium
 - high
 - critical

**Describe the bug**
According to my user's RBAC grants, I should not be able to list clusters, vclusters, or `gitopsclusters` outside of the `test` namespace. On the Clusters dashboard, I see only `management` and the one vcluster that I was expecting to see.

On the `Flux Runtime` tab, I get a list of errors at the top relating to each of the clusters that I should not be able to enumerate.

<img width="1206" alt="Screenshot 2023-02-16 at 7 56 17 PM" src="https://user-images.githubusercontent.com/3286998/219522531-0a3f71d6-46fe-4cb4-818f-5abed196c8ce.png">

I believe this may be a chink in the armor, (is it possible that the list of clusters being available to my user at runtime is a security issue?) I do not believe I can do more than list them, but according to the RBAC, I should not be able to do even that.

**To Reproduce**
I have a `cluster`, `gitopscluster`, and `vcluster` in the namespace `test` (the cluster is called `limnocentral`)

I have this RBAC which is bound to my user through an OIDC group, and I believe there is no other RBAC granted to my account in the management cluster:

The summary of what the RBAC is intended to do:
* I should be able to enumerate and get the objects in the `test` namespace, except for secrets, (but also I can get the user-kubeconfig for my cluster, but excluding the CAPI secret and any other secrets...)
* I should be able to click around the WGE interface without seeing any random errors
* (I should be able to reconcile Flux objects) - of course, these are the patch permissions, they're intended for WGE to use, (and they mean something very different for kubectl)

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: home-guests-cluster-role-binding
  namespace: test
subjects:
  - kind: Group
    name: kingdon-ci:home-guests
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: home-guests-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: home-guests-cluster-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
    resourceNames: ["limnocentral-user-kubeconfig"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list"]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["kustomizations"]
    verbs: ["get", "list", "patch"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["get", "list", "patch"]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: [ "buckets", "helmcharts", "gitrepositories", "helmrepositories", "ocirepositories" ]
    verbs: ["get", "list", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["pac.weave.works"]
    resources: ["policies"]
    verbs: ["get", "list"]
  - apiGroups: ["cluster.x-k8s.io"]
    resources: ["clusters"]
    verbs: ["get", "list"]
  - apiGroups: ["gitops.weave.works"]
    resources: ["gitopsclusters"]
    verbs: ["get", "list"]
  - apiGroups: ["infrastructure.cluster.x-k8s.io"]
    resources: ["vclusters"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: home-guests-list-namespaces
subjects:
  - kind: Group
    name: kingdon-ci:home-guests
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: home-guests-list-namespaces
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: home-guests-list-namespaces
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: ["pac.weave.works"]
    resources: ["policies"]
    verbs: ["get", "list"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list"]
```

The RBAC for the child cluster is more broadly permissioned. I do not believe that should matter here...

I can grant the access to someone who needs triage, this mccp is on the internet 👍 

**Actual behaviour**
I get a lot more information than I should be able to have about which clusters exist, when I visit the "Flux Runtime" page - in the alertbox at the top, I see as many alerts as there are clusters. I cannot list or get any of their GitopsClusters or anything else about them, so I'm not sure why my user is able to see evidence of those clusters.

**Expected behaviour**
I should be able to see and enumerate the clusters and their respective runtimes that are within my RBAC grant, and only those.

**Cloud provider:**
 - Vcluster / Bare Metal K3s

**Additional context**
The host cluster is `howard-moomboo-space` in this repo: https://github.com/kingdon-ci/fleet-infra/tree/main/clusters
and the guest cluster / "tenant workspace" is called `limnocentral`

I have done these RBAC by hand, or copied from examples. This is not a proper "tenant" in the sense of having followed the workspace guide. It is possible there is a mistake in my RBAC (or that there are additional permissions I did not intend to grant...)
