### ISSUE TITLE
The "Kubeconfig" button can forget what namespace the GitopsCluster was in

### ISSUE THREAD

**Issue by kingdonb** [weaveworks/weave-gitops-enterprise#2437]
**WGE release:** 0.17.0

**Kubernetes release:** v1.26.1+k3s1

**Priority**
 - low
 - medium
 - high

**Severity**
 - low
 - medium
 - high
 - critical

**Describe the bug**
There is somewhere in the handling of gitopsclusters where "which namespace" the GitopsCluster belongs to, becomes lost information.

<img width="1404" alt="Screenshot 2023-02-22 at 10 16 54 AM" src="https://user-images.githubusercontent.com/3286998/220667036-dd78d3a2-f6a5-4fdc-8ddb-c3baa73e659f.png">

This is a CAPI-less Weave GitOps Enterprise installation, which I have called "Staging" because I've already got more than enough vclusters, and we don't need any more

The GitopsCluster we clicked on is in the "ext" namespace, but as you can see here WGE is trying to get GitopsClusters in the namespace `default`, which is not something we're permitted to do. This user is restricted to only the things which I thought they needed as a tenant. I granted access to get and list practically everything, but I am not trying to give away the keys to the kingdom so secrets are `watch` and `list` only.

I was aiming to add a user kubeconfig and selectively allow the user to read just that one secret, so the "Kubeconfig" button would remain usable, but I think that `user-kubeconfig` thing is a facet of the capiClusterRef and won't work with `secretRef` gitopsclusters. That's a separate issue. The issue here is that the UI has lost the plot, and sends queries to a namespace it should not be looking into. There is some setup below, ~but I don't have a precise bead on the conditions that create this problem.~ (Edit: I was able to repro this issue reliably by the time I finished writing out this issue report...)

I can give someone access to the "read-only" and to the "cluster-admin" separately, in case you want to take a look at this cluster. It's all on the public internet, running from my home lab.

**To Reproduce**

I have created a namespace "ext" and am populating it with GitopsClusters for the tenant, really there's only one GitopsCluster, I wanted to avoid installing WGE on the tenant cluster, where the tenant might interact with it, and so this is what I came up with.

```
apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: limnocentral
  namespace: ext
spec:
  secretRef:
    name: limnocentral-kubeconfig
```

The kubeconfig there is for WG UI to use for impersonation, it is a copy of the CAPI kubeconfig so that the WG UI has access to everything, but users access gets filtered down to whatever their OIDC token could have seen (that is my understanding from how I configured after reading the docs, at least – I'm pretty sure that's how it's meant to work.) Since this tenant has cluster-admin on the tenant cluster, they can see everything (but on the WGE cluster, they have limited access, cannot read secrets for example.)

I allow list and watch secrets, but not "get" – I'm not 100% sure it's safe to do this, but I'm trying to treat the tenant as a guest on the WGE cluster, and give them a namespaced clusterrole which can inspect the gitopscluster and can observe the state of said cluster in the UI, but shouldn't be able to do anything else, other than listing and getting objects which are not secrets:

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: home-guests-role-binding
  namespace: ext
subjects:
  - kind: Group
    name: kingdon-ci:home-guests
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: home-guests-cluster-role-2
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: home-guests-cluster-role-2
rules:
  - apiGroups: ["gitops.weave.works"]
    resources: ["gitopsclusters"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cluster.x-k8s.io"]
    resources: ["clusters"]
    verbs: ["get", "list", "watch"]
```

The exhaustive permissions list is a bit longer, here:
https://github.com/kingdon-ci/fleet-infra/blob/6fea2fa9c9af0f002f3f2aeda03e9e8612976423/clusters/howard-stage/rbac/wego-admin.yaml
(which should have also been made a public repository by now...)

**Actual behaviour**
The error message indicates that failure condition was reached when WGE attempted to list GitopsClusters in a different namespace than the one which houses the GitopsCluster we clicked on.

Everything is fine on the Clusters page:
<img width="1379" alt="Screenshot 2023-02-22 at 10 35 24 AM" src="https://user-images.githubusercontent.com/3286998/220672940-5e7a77d9-9afa-4f44-b0d2-6f961c391a59.png">

I can click for the cluster, `limnocentral`, which I'm supposed to gain access to:
<img width="1400" alt="Screenshot 2023-02-22 at 10 35 32 AM" src="https://user-images.githubusercontent.com/3286998/220673097-e86e43b5-fe66-4606-939f-e5bc56a118b2.png">

The OIDC passthrough behavior works as expected, I can see inside the cluster (although my user is not restricted there inside the leaf cluster from anything else that WGE is going to allow me to do, so I'm not sure I'd be able to tell the difference if it just gave me full access):
<img width="1394" alt="Screenshot 2023-02-22 at 10 36 45 AM" src="https://user-images.githubusercontent.com/3286998/220673436-9c9fc0d3-656c-4f9f-aaa1-1c7fe906d57a.png">
I'm blocked from reading secrets on the parent cluster where this HelmRelease is hosted, which is expected, and I can see everything on the leaf cluster (including secrets).

But, when I click the Kubeconfig button on the Cluster view, sometimes it works: (this is one of the errors you'd expect to see)
<img width="1407" alt="Screenshot 2023-02-22 at 10 40 43 AM" src="https://user-images.githubusercontent.com/3286998/220674891-0c6eb5da-64e1-42a7-bc2f-32b6ceb8949a.png">

Other times, one way to trigger this issue is to click Kubeconfig before the asynchronous activity that populates namespace completes, instead of waiting for the call to complete, the link assumes the "default" namespace is the right one:
<img width="1404" alt="Screenshot 2023-02-22 at 10 16 54 AM" src="https://user-images.githubusercontent.com/3286998/220678755-77cb4b01-07ea-455f-8f52-307c3c3e0380.png">

It seems with this knowledge, I can reproduce the error reliably. I wasn't doing any special ordered clicking before, so I guess there are other conditions that can trigger the asynchronous activity to fail or take too long, so users might be able to encounter this condition in other ways, but that one works.

**Expected behaviour**
The user should get a more appropriate error message, when they do not have permissions to list secrets in the `GitopsCluster`'s namespace, or when the `{{clustername}}-kubeconfig` and `{{clustername}}-user-kubeconfig` secrets can neither be retrieved.

The user should not be reaching into the incorrect namespace (`default`) when the GitopsCluster isn't in that namespace.

I'll probably make a separate report, unless you tell me it's something we can fix in the same breath, but it's a bit more than a minor inconvenience that `secretRef` doesn't have an additional handle for the `{{clustername}}-user-kubeconfig` so I can provide one with the proper OIDC configuration for the leaf cluster users' to access this environment and any nearby neighbors we've curated for them. (That was a very handy feature in the `capiClusterRef` version of `GitopsCluster`! Now I want more of it...)

**Cloud provider:**
 - Vcluster (bare metal + CAPI, externally hosted)

**Additional context**
Some of the screenshots in the original post were incorrect. I have fixed them up now, (if you are looking at a live copy on GitHub rather than what came through your e-mail, then you should be able to see what I saw, please LMK if anything is still unclear...)
