### ISSUE TITLE
Implement a template to bootstrap SOPS on leaf clusters

### ISSUE THREAD

**Issue by serboctor** [weaveworks/weave-gitops-enterprise#2517]
### Background

Proposing a more generic and integrated way to generate SOPS keys and distribute them through WGE cluster provisioning process.

### 1- Template Updates
- It should have annotation `templates.weave.works/sops-enabled: "true"` to enable WGE to create the kustomization in cluster creation
- It should have the following values that’s needed for kustomization
```yaml
- name: SOPS_KUSTOMIZATION_NAME
  required: false
  description: Define sops kustomization name. (my-secrets)
- name: SOPS_KUSTOMIZATION_GIT_REPO_NAME
  required: false
  description: Define sops git repo name. (flux-system)
- name: SOPS_KUSTOMIZATION_PATH_IN_GIT_REPO
  required: false
  description: Define sops path in git repo. (./sops)
```

- It should have the following annotations to hold the kustomization values otherwise templates controller will discard them
```yaml
weave.works/sops-kustomization: "bootstrap-${SOPS_KUSTOMIZATION_NAME}"
weave.works/sops-repo: "repo-${SOPS_KUSTOMIZATION_GIT_REPO_NAME}"
weave.works/sops-path: "path-${SOPS_KUSTOMIZATION_PATH_IN_GIT_REPO}"
```

- It should have the following label

```yaml
weave.works/flux: "bootstrap"
```

### ClusterBootStrap Controller job

We will need a job to run in the bootstrapping of leaf cluster to install sops and generate the keys and to be used in the cluster template
