### ISSUE TITLE
UI Terraform Change Terraform Icon when waiting for a Plan

### ISSUE THREAD

**Issue by chanwit** [weaveworks/weave-gitops-enterprise#2745]
Reported by @souleb Right now when a Terraform deployment is waiting for a plan, it displays the same icon as an error. 
A different icon would be nice so users could tell what is an error/success, or just waiting to be passed a plan id.

Interlock: https://github.com/weaveworks/weave-gitops-interlock/issues/388

### User story

As a Terraform user, I'd like to see a distinct icon for deployments waiting for a plan, so that I can easily differentiate between error states, success states, and pending plan actions.

### Acceptance Criteria

- When a Terraform deployment is waiting for a plan, a unique icon should be displayed, visually distinct from the error and success icons.
- The icon should be easily recognizable and understandable, clearly representing the waiting or pending state.
- The waiting icon should be used only when the Terraform object message starts with `Plan generated:`.

Example:
```
status:
  conditions:
  - lastTransitionTime: "2023-04-27T13:31:53Z"
    message: 'Plan generated: set approvePlan: "plan-main-a570bd8109" to approve this plan.'
    reason: TerraformPlannedWithChanges
    status: Unknown
    type: Ready
  - lastTransitionTime: "2023-04-27T13:32:08Z"
    message: Plan generated
    reason: TerraformPlannedWithChanges
    status: "True"
    type: Plan
  lastAttemptedRevision: main/a570bd81090f78cf9276dc61a0f0c1ce59d56df4
  lastPlannedRevision: main/a570bd81
```
