### ISSUE TITLE
Display template.description on the "Render template page"

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#2773]
https://github.com/weaveworks/weave-gitops-interlock/issues/397

Use case:
> It would be helpful to display the description as that is the only way we can add explanation and notes to a template to display when being used.

_Could_ be markdown, if there's a nice way to actually write markdown in the template?
e.g.
```yaml
apiVersion: templates.weave.works/v1alpha2
kind: GitOpsTemplate
metadata:
  name: vcluster-template-development
  namespace: default
  annotations:
    templates.weave.works/profiles-enabled: "true"
    templates.weave.works/add-common-bases: "true"
spec:
  description: |
    # A simple capv template
    ## instructions
  params:
```

Tasks
- [x] update render template
- [x] make sure the templates table description column is still usable, either by ellipsis or just including the first line.
