### ISSUE TITLE
Confusing to configure ingress w/ Traeffik

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#2820]
We tell people to configure tls via the HelmRelease values.yaml:

```
tls:
  enabled: false
```

BUT! The service will still advertise the port as `https`, this can be overridden:

```
    service:
      type: ClusterIP
      ports:
        http: 8000
        https: {}
      targetPorts:
        http: 8000
```

And traeffik will then send http.

How can we make this easier?
