### ISSUE TITLE
flux-shard-controller should use existing in-cluster flux-controllers as a template

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#2847]
Maintaining a copy of the flux controller deployment manifests is expensive:
1. More code to maintain
2. Have to keep them up to date
3. Pain to write out the golang obj. literals in the first place. Though @bigkevmcd did it already here! :star: https://gist.github.com/bigkevmcd/09951168c607b8807d5ee19932049567

A solution is to use the existing flux deployments in the cluster as a template instead.

Given

```
apiVersion: templates.weave.works/v1alpha1
kind: FluxShardSet
metadata:
  name: fluxshardset-sample
  namespace: flux-system
spec:
  type: kustomization
  shards:
    - name: shard1
    - name: shard2
```

We could get the `flux-system/$spec.type-controller` (in this case `flux-system/kustomize-controler`) `Deployment`, then
- Remove all the transient fields / annotations (status, createdAt, revision etc etc)
- Add the sharding cli flag
- Update the name to `kustomize-controller-$shardName`
- Re-apply to the cluster

And we should end up with 2 `Deployments`:
- `flux-system/kustomization-controller-shard1`
- `flux-system/kustomization-controller-shard2`

## Tasks

- Update the reconcile loop to watch Deployments?
- Add RBAC in flux-shard-ctrl to allow get/watch deployments
- Clean deployments of transient / status etc
- Update deployments with correct cli flags
- Do a pre-flight check of the existing controller to check it is scoped down to ignore sharded resources.
