### ISSUE TITLE
flux-shard-contoller should generate deployments when reconciling a FluxShardSet

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#2848]
Given 

```
apiVersion: templates.weave.works/v1alpha1
kind: FluxShardSet
metadata:
  name: fluxshardset-sample
spec:
  type: kustomize
  shards:
    - name: shard1
    - name: shard2
```

When this CR is applied to the cluster, 2 new `Deployments` should be applied in the cluster:

- `flux-system/kustomize-controller-shard1`
- `flux-system/kustomize-controller-shard2`

If a shard is removed from the list of shards and the CR is re-applied, then the associated deployment should be deleted. E.g we need to keep track of deployments, probably using a system like gitopssets' inventory

### Tasks

- Create `Deployment`s from a template, great sample here https://gist.github.com/bigkevmcd/09951168c607b8807d5ee19932049567
- Store created deployments in an inventory (like gitopssets)
- If a deployment already exists then PATCH it back to its expected state that we created it in
- If a shard exists in the inventory but not in the spec.shards then DELETE it and update the inventory
