### ISSUE TITLE
Change `upgrade` command to install new-helm-style profiles

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#298]
`gitops upgrade` should create a pull request to create two files:
1. `.weave-gitops/clusters/$cluster-name/system/enterprise/helm-repository.yaml`
2. `.weave-gitops/clusters/$cluster-name/system/enterprise/helm-release.yaml`
3. `.weave-gitops/clusters/$cluster-name/system/enterprise/kustomization-apps-capi.yaml`

Where 3. sync's all the new capi clusters:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: my-management-cluster
  namespace: wego-system
resources:
- ../../../../apps/capi
```
