### ISSUE TITLE
flux-shard-controller allow user to configure the labelselector of each shard

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#3085]
User story: sometimes users already have many labels configured on their flux resources (helmrepos/gitops/helmreleases), and may want to shard based on one of those labels instead of manually adding "shard1", "shard2" etc to each flux resource in git themselves.

Right now the FluxShardSet looks like this:

```
apiVersion: templates.weave.works/v1alpha1
kind: FluxShardSet
metadata:
  name: fluxshardset-sample
  namespace: flux-system
spec:
  sourceDeploymentRef:
    name: kustomize-controller
    namespace: flux-system
  shards:
    - name: shard1
    - name: shard2
```

We want to add support for specifying a custom label selector:

```
  shards:
    - name: shard1
      labelSelector: app.kubernetes.io/component in (billing-app, metrics-app)
```

Code changes
- Instead of setting the watch-label-selector to the shard.name, set it to shard.labelSelector
- We should also throw an error if the labels between multiple FluxShardSets overlap.
  - labelselector libs (golang) have support for detecting overlapping labels (probably the `labels` package)

References
- Other fun things you can do w/ labelSelectors https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api
