### ISSUE TITLE
application details inventory breaks with unexpected token for kustomization

### ISSUE THREAD

**Issue by enekofb** [weaveworks/weave-gitops-enterprise#3172]
First raised in https://github.com/weaveworks/weave-gitops-enterprise/issues/3054#issuecomment-1625106118
Happens in weave gitops > 0.28

Given lastest weave gitops 
And created the following resources
```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo-ga
spec:
  interval: 10m
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-ga
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: podinfo-ga
  path: "./kustomize"
  prune: true
  timeout: 1m
```
When I go to `podinfo-ga` kustomization details view 

**Current Behaviour** 
Then I could see the following error
<img width="1076" alt="Screenshot 2023-08-07 at 08 52 01" src="https://github.com/weaveworks/weave-gitops-enterprise/assets/12957664/140e3df3-83f5-46e6-9aef-15ff0c406d9b">

And underlying inventory api call like

```bash 
curl 'https://fluxga.eng-sandbox.weave.works./v1/inventory?name=podinfo-ga&namespace=explorer-validation&kind=Kustomization&clusterName=management&withChildren=true' 
...
```

with response 
```bash
HTTP/1.1 502 Bad Gateway
Date: Mon, 07 Aug 2023 07:53:14 GMT
Content-Type: text/html
Content-Length: 552
Connection: keep-alive

<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
and logs  shows panic

```
2023/08/07 07:56:13 http: panic serving 192.168.136.37:58788: runtime error: invalid memory address or nil pointer dereference
goroutine 5424504 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1854 +0xbf
panic({0x3532080, 0x607bdd0})
	/usr/local/go/src/runtime/panic.go:890 +0x263
github.com/weaveworks/weave-gitops/core/server.(*coreServer).getKustomizationInventory(0xc000213620, {0x4340568?, 0xc0295341b0}, {0xc026703bdf, 0xa}, {0x4355a00, 0xc000146c40}, {0xc026703b97, 0xa}, {0xc026703bac, ...}, ...)
	/go/pkg/mod/github.com/weaveworks/weave-gitops@v0.29.0/core/server/inventory.go:74 +0x178
github.com/weaveworks/weave-gitops/core/server.(*coreServer).GetInventory(0xc000213620, {0x4340568, 0xc0295341b0}, 0xc0017f2930)
	/go/pkg/mod/github.com/weaveworks/weave-gitops@v0.29.0/core/server/inventory.go:44 +0x29e
github.com/weaveworks/weave-gitops/pkg/api/core.local_request_Core_GetInventory_0({0x4340568, 0xc0295341b0}, {0x35301c0?, 0x632ad80?}, {0x4360d80, 0xc000213620}, 0xc02690d000, 0x30?)
	/go/pkg/mod/github.com/weaveworks/weave-gitops@v0.29.0/pkg/api/core/core.pb.gw.go:571 +0x162
github.com/weaveworks/weave-gitops/pkg/api/core.RegisterCoreHandlerServer.func16({0x432f720, 0xc00f2c9d10}, 0xc02690d000, 0xc0000bbee0?)
	/go/pkg/mod/github.com/weaveworks/weave-gitops@v0.29.0/pkg/api/core/core.pb.gw.go:1148 +0x205
github.com/grpc-ecosystem/grpc-gateway/v2/runtime.(*ServeMux).ServeHTTP(0xc00071fe00, {0x432f720, 0xc00f2c9d10}, 0xc02690d000)
	/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.10.2/runtime/mux.go:386 +0x9e6

```
