### ISSUE TITLE
Add granular controls for turning Explorer on and off for different parts of the UI

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops-enterprise#3424]
To aid in adoption of Explorer and query service, we want users (WW SWEs) to be able to set environment variables to enable or disable explorer for different parts of the UI.

We could add a map to the helm chart here: 

https://github.com/weaveworks/weave-gitops-enterprise/blob/243d77974e275d1bb27f019b9f88f002bb34fd35/charts/mccp/values.yaml#L221C10-L221C10

This might look something like:

```yaml
components:
  applications: true
  souces: true
  gitopsclusters: true
```

These mapping items will need to be converted into feature flags that are then consumed in the UI to determine which component to render.
