### ISSUE TITLE
HPA appears as not ready while Kustomization is ready

### ISSUE THREAD

**Issue by yiannistri** [weaveworks/weave-gitops-enterprise#3529]
Let's investigate why the HPA appears as Not Ready while the Kustomization is Ready. 

I've used these manifests:
```
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m
  url: https://github.com/stefanprodan/podinfo
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: podinfo
  path: "./kustomize"
  prune: true
  timeout: 1m
```

Noticed this in WGE but the fix for this may end up in OSS.

<img width="1575" alt="Screenshot 2023-10-20 at 15 21 45" src="https://github.com/weaveworks/weave-gitops-enterprise/assets/8741709/1659f9ed-7dd5-4140-9b5b-ac9515c60451">
