### ISSUE TITLE
Not handling empty inventory in GitOpsSet

### ISSUE THREAD

**Issue by bigkevmcd** [weaveworks/weave-gitops-enterprise#3726]
**Describe the bug**
When the inventory is empty (0 resources created) we get an error.

```yaml
status:
  conditions:
    - lastTransitionTime: 2023-12-14T00:20:05Z
      message: 0 resources created
      reason: ReconciliationSucceeded
      status: "True"
      type: Ready
  observedGeneration: 2
```

<img width="690" alt="image" src="https://github.com/weaveworks/weave-gitops-enterprise/assets/867746/a8addb1c-4026-4d81-9251-c5b4ffad7c2c">

**To Reproduce**
Create a GitOpsSet that doesn't generate any resources, perhaps with an empty list.

There's a bug filed already to do some validation of the spec requiring some generated resources.

(lists should not be allowed to be empty)

But this could happen if no `GitopsClusters` matched the labels etc.

**Actual behaviour**
See error message above

**Expected behaviour**
No error, perhaps a message showing that there are no resources generated.

**Additional context**

- Weave GitOps version:
- Kubernetes version:
