### ISSUE TITLE
[cluster-reflector] Allow filtering out "self" (e.g. if user moves/"pivot"s their CAPI cluster)

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#3739]
General solution

```
kind: ACD
spec:
  exclude: ["my-capi-cluster"] # if there's a eks/aks cluster.
  exclude: ["<capi-UID>"] # if there's a capi
```

Specific to CAPI:

```
kind: ACD
spec:
  capi:
    clusterID: <uid of the capi object that is the hosting cluster>
```

^ ClusterID here is a bit awkward to look up and manage and debug (its a UID).

```
kind: ACD
spec:
  capi:
    currentClusterName: 
    managementClusterName: my-cluster # <--- this one, CAPI using the terminology
    selfClusterName:
```

**Decision**

Lets go w/ the `spec.capi.managementClusterName` solution, it aligns w/ the automatic solution we have eks/aks, and then we can always identify the "management" cluster for all providers, which may come in handy in the future.
