### ISSUE TITLE
Pipelines are not working

### ISSUE THREAD

**Issue by gecube** [weaveworks/weave-gitops-enterprise#3755]
Hello!

I just installed weave gitops enterprise and trying to play with it.
When I go to pipelines interface, I got the error. Please refer to the video

https://github.com/weaveworks/weave-gitops-enterprise/assets/2912732/06e691a2-870a-46c9-8cd5-ed6207848928

The installation of gitops was done with FluxCD manifests attached below:

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops-enterprise-charts
  namespace: flux-system
spec:
  interval: 1m0s
  secretRef:
    name: weave-gitops-enterprise-credentials
  url: https://charts.dev.wkp.weave.works/releases/charts-v3
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops-enterprise
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mccp
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: weave-gitops-enterprise-charts
        namespace: flux-system
      version: 0.38.1
  install:
    crds: CreateReplace
  interval: 1h0m0s
  upgrade:
    crds: CreateReplace
  values:
    cluster-controller:
      controllerManager:
        manager:
          image:
            repository: docker.io/weaveworks/cluster-controller
            tag: v1.5.2
      enabled: true
      fullnameOverride: cluster
    config: {}
    enablePipelines: true
    gitopssets-controller:
      controllerManager:
        manager:
          args:
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=127.0.0.1:8080
          - --leader-elect
          - --enabled-generators=GitRepository,Cluster,PullRequests,List,APIClient,Matrix,Config
      enabled: true
    global: {}
    ingress:
      annotations: {}
      className: ""
      enabled: false
      hosts:
      - host: ""
        paths:
        - path: /
          pathType: ImplementationSpecific
      service:
        name: clusters-service
        port: 8000
      tls: []
    service:
      annotations: {}
      clusterIP: ""
      externalIPs: []
      externalTrafficPolicy: ""
      healthCheckNodePort: 0
      loadBalancerIP: ""
      loadBalancerSourceRanges: []
      nodePorts:
        http: ""
        https: ""
        tcp: {}
        udp: {}
      port:
        https: 8000
      targetPort:
        https: 8000
      type: ClusterIP
    tls:
      enabled: false
```

The access to the console was gotten by `kubectl port-forward`
