### ISSUE TITLE
Running the upgrade command on cluster that has already been upgraded adds an extra kustomization line

### ISSUE THREAD

**Issue by steve-fraser** [weaveworks/weave-gitops-enterprise#559]
**WGE release:**
 - which wge release
v0.0.19

**Kubernetes release:**
 - which kubernetes release

v1.21.2

**Priority**
 - low 
 - medium
 - high

low

**Describe the bug**
I ran the upgrade command on an already upgraded cluster:
gitops upgrade --config-repo git@github.com:steve-fraser/mvm-mgmt-cluster.git --version 0.0.19

Which results in 
````
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kind-mvm-mgmt-cluster
  namespace: wego-system
resources:
- weave-gitops-enterprise.yaml
- weave-gitops-enterprise.yaml
- gitops-runtime.yaml
- flux-source-resource.yaml
- flux-system-kustomization-resource.yaml
- flux-user-kustomization-resource.yaml
```
**To Reproduce**
Steps to reproduce the behaviour:
1. Install weave gitops 
2. Upgrade cluster
3. Upgrade cluster again

**Expected behaviour**
A clear and concise description of what you expected to happen.

Not add an additional kustomization line

**Cloud provider:**
 - AWS
 - Azure
 - Equinix
 - GCP
 - VMware
 - LiquidMetal

KIND
**Additional context**
Add any other context about the problem here.
