### ISSUE TITLE
Non-namespaced objects get the namespace appended to it

### ISSUE THREAD

**Issue by steve-fraser** [weaveworks/weave-gitops-enterprise#621]
**WGE release:**
 - which wge release

v0.0.19

**Kubernetes release:**
 - which kubernetes release
v1.21.2
**Priority**
 - low 
 - medium
 - high

low
**Describe the bug**

```
apiVersion: capi.weave.works/v1alpha1
kind: CAPITemplate
metadata:
  name: capd-microvm
  namespace: default
spec:
  description: CAPI Microvm Demo
  params:
    - name: NAMESPACE
      description: Namespace to create the cluster in.
  resourcetemplates:
    - apiVersion: v1
      kind: Namespace
      metadata: 
        name: "${NAMESPACE}"
```

Creating a object given the above CAPI template parameters and namespace.
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: test5
  namespace: default
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Add template
2. Create cluster

**Expected behaviour**

**Cloud provider:**
 - AWS
 - Azure
 - Equinix
 - GCP
 - VMware
 - LiquidMetal

LiquidMetal
**Additional context**
