### ISSUE TITLE
Template Helm Chart Values for Profiles

### ISSUE THREAD

**Issue by steve-fraser** [weaveworks/weave-gitops-enterprise#704]
**Priority**
high
**Describe the feature**
At Protocol Labs, We are creating roles and policies within the CAPI template.

For example:
```
  - apiVersion: iam.aws.crossplane.io/v1beta1
    kind: Role
    metadata:
      name: ${CLUSTER_NAME}-ebs-csi-controller
    spec:
      providerConfigRef:
        name: sti-provider
      forProvider:
        assumeRolePolicyDocument: |
          {
              "Version": "2012-10-17",
              "Statement": [
                  {
                      "Sid": "",
                      "Effect": "Allow",
                      }
                  }
              ]
          }
```
We are ensuring a 1:1 ratio between clusters and roles, which requires us to add the cluster name to the role as seen above. 

The Kubernetes `Service Account` needs to be annotated with the arn annotation which includes the cluster name.

the account is static so it is not required to be accessible in the helm chart, but the ability to access the cluster name is required to render the annotation.  
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-csi-controller-sa
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::407967248065:role/dev-v2-ebs-csi-controller"
```
Example on how this would be used with the above setup

Template values file
```
cluster:
    name: ${CLUSTER_NAME}
```

service account helm template
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-csi-controller-sa
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::407967248065:role/{{ .Values.cluster.name }}-ebs-csi-controller"
```

Rendered helm release
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  labels:
    weave.works/applied-layer: layer-1
  name: dev-v2-ebs-csi-controller
  namespace: wego-system
spec:
  chart:
    spec:
      chart: ebs-csi-controller
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta1
        kind: HelmRepository
        name: weaveworks-charts
        namespace: wego-system
      version: 0.0.5
  interval: 1m0s
  values:
    custer:
      name: dev-v2
```

**Cloud provider:**
 - AWS
 - Azure
 - Equinix
 - GCP
 - VMware
 - LiquidMetal

**Additional context**
