### ISSUE TITLE
Add canaries gate handler

### ISSUE THREAD

**Issue by luizbafilho** [weaveworks/weave-gitops-enterprise#826]
Add canaries gate handler to allow users to use to set the webhook spec on canaries definitions:

```yaml
analysis:
    webhooks:
      - name: "start gate"
        type: confirm-rollout
        url: https://weave-gitops-enterprise.flux-system/v1/canaries/gate
```
