### ISSUE TITLE
GitopCluster readiness might not work with EKS/AKS capi clusters

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops-enterprise#909]
**Current behaviour in the clusters-controller**

For **capiClusterRef**:

```
apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  name: dummy-05
  namespace: default
spec:
  capiClusterRef:
    name: dummy-05
```

This is `Ready: True` when we can connect, see at least 1 CP `node`, and that all the CP `node`s are Ready.

For **secretRef**:

```
apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  name: dummy-04
  namespace: default
spec:
  secretRef:
    name: dummy-04-kubeconfig
```

If the secret exists, the cluster is ready.

**Problem with this**

The capiClusterRef case _might_ not work for clusters that do not have any CP nodes (EKS/AKS/GKE - though there is no capi provider for GKE right now).

**Other considerations**

We have an open PR to switch secretRef to also check for CP readiness. The motivation for this is to only start MC-querying **Ready** clusters, so we should do a full check on them too. This would have the same issue w/ EKS/AKS.

**Types of readiness that would be useful**
- CP is ready: mainly so CNI can be installed smoothly, not needed for EKS/AKS!
- We can successfully connect with a kubectl client: so we know the secret is working.
