### ISSUE TITLE
Profiles failed to get installed in targeted namespace

### ISSUE THREAD

**Issue by saeedfazal** [weaveworks/weave-gitops-enterprise#974]
The profiles for capi clusters failed to get installed in the non-default `flux-system` namespace.
For example when user choose to install cert-manager  profile in cert-manager namespace, it fails as the targeted namespace doesn't exist in the newly created capi cluster.

Capi cluster profiles yaml:
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  creationTimestamp: null
  name: weaveworks-charts
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 1m0s
  url: https://s3.us-east-1.amazonaws.com/weaveworks-wkp/temp-repo
status: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  labels:
    weave.works/applied-layer: layer-0
  name: ui-end-to-end-capd-cluster-cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: HelmRepository
        name: weaveworks-charts
        namespace: flux-system
      version: 0.0.7
  install:
    crds: CreateReplace
  interval: 1m0s
  targetNamespace: cert-manager
  values:
    installCRDs: true
status: {}

```

Capi cluster helm controller logs:
```
apd-cluster-cert-manager","namespace":"flux-system"}
{"level":"error","ts":"2022-06-21T15:42:05.780Z","logger":"controller.helmrelease","msg":"Reconciler error","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"ui-end-to-end-capd-cluster-cert-manager","namespace":"flux-system","error":"Helm install failed: namespaces \"cert-manager\" not found"}
{"level":"info","ts":"2022-06-21T15:42:06.592Z","logger":"controller.helmrelease","msg":"reconcilation finished in 61.432308ms, next run in 1m0s","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"ui-end-to-end-capd-cluster-cert-manager","namespace":"flux-system"}
```
