### ISSUE TITLE
spike: flagger in one click

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops-enterprise#983]
Feedback from SAs/CX is that it would be hugely beneficial in sales engagements if we were able to show an easy on-ramp into progressive delivery. The counter side to this being that without said capability, the implementation burden will appear too great for a number of prospects.

The ideal scenario is:
- As a user, I can select my application, and click "enable progressive delivery" and ✨ 

A non-exhaustive list of things that block this:
- what is an application?
- have they got a service mesh installed and appropriately configured?
- is Flagger installed and appropriately configured?
- does the "application" have a service defined already?
- does the "application" have multiple containers
- does the "application" expose multiple ports?
- which deployment strategy do they want to use?
- etc, etc.

I would like help in evaluating the following idea, or for any other ideas to be brought forward:

What if we could present something which _might_ work - even with massive caveats, but is also configurable so that the user could in theory make it more probable to work?

> what is an application?

A deployment. We present a list of deployments across clusters, and it is on this object we offer the ability to enable progressive delivery.

> is Flagger installed and appropriately configured / have they got a service mesh installed and appropriately configured

Assume so. Test using the Linkerd Flagger profile as a known and demoable configuration.

> which deployment strategy do they want to use?

Canary rollout by default.

> does the "application" have a service defined already?

Investigate how Flagger handles this

> does the "application" have multiple containers / does the "application" expose multiple ports

Pick the first one we find.

Consider this pseudo config (it is just meant to illustrate the idea rather than be in anyway accurate), doesn't have to be a template, the idea is that we take the basic getting started example Canary object, attempt to provide key values as substitutions based on the selected deployment, and then - similar to our create cluster workflows - the user has the option to preview the PR/edit the YAML or submit and hope for the best.

```
apiVersion: flagger.app/v1beta1
kind: CanaryTemplate
metadata:
  name: ${deployment.spec.selector.matchLabels.app }
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${ deployment.spec.selector.matchLabels.app }
  service:
    port: ${deployment.spec.template.spec.containers[0].port[0].containerport}
  analysis:
    interval: 1m
    threshold: 10
    maxWeight: 50
    stepWeight: 5
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m
      - name: request-duration
        thresholdRange:
          max: 500
        interval: 1m
    webhooks:
      - name: load-test
        url: http://flagger-loadtester.test/
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://${deployment.spec.selector.matchLabels.app}-canary.test:${deployment.spec.template.spec.containers[0].port[0].containerport}/"
```

We know the deployment's source/kustomization, so in theory we could extract an appropriate path in which to commit the canary.yaml object. Again this could be something which is overridable by the user.

Spike outcome: evaluated above proposal for feasibility, including discussion with key stakeholders, optionally - proposed alternatives. 

Timebox: 2hrs
